# **0: Importing Pandas and 311 Datasets, 2020-2025**

## Importing pandas.

In [156]:
import pandas as pd

### Making all columns visible in imported CSV files.

In [157]:
pd.set_option('display.max_columns', None)

## Importing datasets.

### Importing **2025** dataset for 311 complaints, then testing.

In [158]:
df_25 =  pd.read_csv("jack-data/311_2025.csv", dtype = str)
df_25.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,SERVICEORDERSTATUS,STATUS_CODE,PRIORITY,DETAILS,WARD,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GLOBALID,CREATED,EDITED,OBJECTID
0,401366.060000002,134524.870000001,25-00000002,1438 K STREET SE,WASHINGTON,DC,20003,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2025/01/01 05:22:23+00,2025/01/25 16:50:59+00,2025/01/10 04:59:00+00,2025/01/01 05:22:23+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,Ward 6,401366.06,134524.87,38.87855545,-76.98425653,63442,{2AA431E0-F9C7-766F-E063-792F520A1480},NaN,NaN,11865239
1,396942.869999997,140394.800000001,25-00000003,1511 PARK ROAD NW,WASHINGTON,DC,20010,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2025/01/01 05:23:49+00,2025/01/01 05:42:41+00,2025/01/02 05:23:49+00,2025/01/01 05:23:49+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,Ward 1,396942.87,140394.8,38.93142958,-77.03525872,234437,{2AA431E0-F9C8-766F-E063-792F520A1480},NaN,NaN,11865240
2,393757.079999998,140604.280000001,25-00000004,3614 MACOMB STREET NW,WASHINGTON,DC,20016,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2025/01/01 05:24:13+00,2025/01/14 17:46:20+00,2025/01/11 04:59:00+00,2025/01/01 05:24:13+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,Ward 3,393757.08,140604.28,38.93329944,-77.0720032,328204,{2AA431E0-F9C9-766F-E063-792F520A1480},NaN,NaN,11865241
3,401561.799999997,133400.440000001,25-00000005,1728 16TH STREET SE,WASHINGTON,DC,20020,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2025/01/01 05:28:59+00,2025/01/23 17:57:19+00,2025/01/09 04:59:00+00,2025/01/01 05:28:59+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,Ward 8,401561.8,133400.44,38.86842581,-76.98200323,56949,{2AA431E0-F9CA-766F-E063-792F520A1480},NaN,NaN,11865242
4,399909.210000001,137153.670000002,25-00000007,327 K STREET NE,WASHINGTON,DC,20002,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2025/01/01 05:29:54+00,2025/01/25 13:15:44+00,2025/01/10 04:59:00+00,2025/01/01 05:29:54+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,Ward 6,399909.21,137153.67,38.90223772,-77.00104668,37329,{2AA431E0-F9CB-766F-E063-792F520A1480},NaN,NaN,11865243

### Importing **2024** dataset for 311 complaints, then testing.

In [159]:
df_24 =  pd.read_csv("jack-data/311_2024.csv")
df_24.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,WARD,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,STATUS_CODE,SERVICEORDERSTATUS,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,PRIORITY,DETAILS,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GLOBALID,CREATED,EDITED,SE_ANNO_CAD_DATA,OBJECTID
0,398931.65,142784.180,24-00000013,5122 NEW HAMPSHIRE AVENUE NW,WASHINGTON,DC,20011.0,Ward 4,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2024/01/01 07:02:11+00,2024/01/09 19:41:49+00,2024/01/10 04:59:00+00,2024/01/01 07:02:11+00,NaN,Closed,NaN,NaN,NaN,Standard,NaN,398931.650000,142784.180000,38.952958,-77.012325,259384,{0DDE2DA2-2F6A-647C-E063-792F520A6A54},NaN,NaN,NaN,11264889
1,397426.26,143264.027,24-00000033,13TH STREET NW AND LONGFELLOW STREET NW,WASHINGTON,DC,20011.0,Ward 4,SPSTDAMA,Traffic Safety Input,Department of Transportation,DDOT,1,2024/01/01 12:46:57+00,2024/01/01 12:54:05+00,2024/01/02 12:46:57+00,2024/01/01 12:46:57+00,NaN,Closed,NaN,NaN,NaN,Standard,NaN,397426.259996,143264.027025,38.957278,-77.029694,901770,{0DE2FF5E-4ED1-278E-E063-792F520ABCD2},NaN,NaN,NaN,11264890
2,403311.22,134980.440,24-00000045,3125 E STREET SE,WASHINGTON,DC,20019.0,Ward 7,S0000,Abandoned Vehicle - On Public Property,PEMA- Parking Enforcement Management Administr...,DPW,1,2024/01/01 13:39:26+00,2024/01/05 13:46:58+00,2024/01/18 13:39:26+00,2024/01/01 13:39:26+00,NaN,Canceled,NaN,NaN,NaN,Standard,NaN,403311.220000,134980.440000,38.882654,-76.961837,39881,{0DE3A04B-F3D2-0B73-E063-792F520ABBA9},NaN,NaN,NaN,11264891
3,406498.92,135695.990,24-00000046,15 53RD PLACE SE,WASHINGTON,DC,20019.0,Ward 7,S0311,Rodent Inspection and Treatment,DOH- Department Of Health,DOH,1,2024/01/01 13:40:25+00,2024/01/02 15:36:35+00,2024/01/08 13:40:25+00,2024/01/01 13:40:25+00,NaN,Closed,NaN,NaN,NaN,Standard,NaN,406498.920000,135695.990000,38.889082,-76.925091,62678,{0DE3A04B-F3D3-0B73-E063-792F520ABBA9},NaN,NaN,NaN,11264892
4,398050.08,143079.590,24-00000059,5400 7TH STREET NW,WASHINGTON,DC,20011.0,Ward 4,S05SL,Streetlight Repair Investigation,Transportation Operations Administration,DDOT,1,2024/01/01 14:17:28+00,2024/01/04 12:59:13+00,2024/01/10 14:17:28+00,2024/01/01 14:17:28+00,NaN,Closed,NaN,NaN,NaN,Standard,NaN,398050.080000,143079.590000,38.955618,-77.022497,250268,{0DE44138-2C7A-1D36-E063-792F520A7FC1},NaN,NaN,NaN,11264893

### Importing **2023** dataset for 311 complaints, then testing.

In [160]:
df_23 =  pd.read_csv("jack-data/311_2023.csv")
df_23.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,WARD,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,SERVICEORDERSTATUS,STATUS_CODE,DETAILS,PRIORITY,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GLOBALID,CREATED,EDITED,SE_ANNO_CAD_DATA,OBJECTID
0,398389.57,138810.810,23-00000008,2019 5TH STREET NW,WASHINGTON,DC,20001.0,Ward 1,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2023/01/01 05:54:29+00,2023/01/01 11:36:13+00,2023/01/03 05:54:28+00,2023/01/01 05:54:29+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,398389.570000,138810.810000,38.917164,-77.018570,229609,{F12E953E-26CA-1E18-E053-782F520AC63D},NaN,NaN,NaN,10579627
1,399970.25,134587.110,23-00000013,401 I STREET SE,WASHINGTON,DC,20003.0,Ward 6,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2023/01/01 06:28:39+00,2023/01/01 11:36:53+00,2023/01/03 06:28:38+00,2023/01/01 06:28:39+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,399970.250000,134587.110000,38.879117,-77.000343,288070,{F12F0091-4F4F-7AFF-E053-782F520A8FBD},NaN,NaN,NaN,10579628
2,396870.76,137775.610,23-00000016,1 SCOTT CIRCLE NW,WASHINGTON,DC,20036.0,Ward 2,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2023/01/01 07:27:54+00,2023/01/01 11:37:30+00,2023/01/03 07:27:53+00,2023/01/01 07:27:54+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,396870.760000,137775.610000,38.907835,-77.036078,226023,{F12FD71E-2F7B-73EA-E053-782F520A3044},NaN,NaN,NaN,10579629
3,396618.45,139476.897,23-00000019,17TH STREET NW AND EUCLID STREET NW,WASHINGTON,DC,20009.0,Ward 1,11,Dead Animal Collection,SWMA- Solid Waste Management Admistration,DPW,1,2023/01/01 11:25:58+00,2023/01/03 19:49:13+00,2023/01/04 11:25:58+00,2023/01/01 11:25:58+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,396618.450011,139476.897005,38.923159,-77.038996,903153,{F133316E-92E2-3EF1-E053-782F520A0ED7},NaN,NaN,NaN,10579630
4,396444.08,139396.240,23-00000031,2375 CHAMPLAIN STREET NW,WASHINGTON,DC,20009.0,Ward 1,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2023/01/01 12:11:44+00,2023/01/01 12:30:20+00,2023/01/03 12:11:44+00,2023/01/01 12:11:44+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,396444.080000,139396.240000,38.922432,-77.041006,284376,{F133D25D-1A13-669C-E053-782F520A7D47},NaN,NaN,NaN,10579631

### Importing **2022** dataset for 311 complaints, then testing.

In [161]:
df_22 =  pd.read_csv("jack-data/311_2022.csv", dtype = str)
df_22.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,WARD,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,SERVICEORDERSTATUS,STATUS_CODE,DETAILS,PRIORITY,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GIS_ID,GLOBALID,CREATED,EDITED,OBJECTID,SE_ANNO_CAD_DATA
0,397507.439999998,140803.780000001,22-00000005,3620 11TH STREET NW,WASHINGTON,DC,20010,Ward 1,S0441,Trash Collection - Missed,SWMA- Solid Waste Management Admistration,DPW,1,2022/01/01 05:20:59+00,2022/01/12 21:45:32+00,2022/01/05 05:20:59+00,2022/01/01 05:20:59+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,397507.44,140803.78,38.93511558,-77.02874886,230397,NaN,{D4800EAA-488F-7440-E053-792F520AC392},NaN,NaN,10050224,NaN
1,397653.869999997,140003.18,22-00000006,3003 11TH STREET NW,WASHINGTON,DC,20001,Ward 1,S0181,Illegal Dumping,SWMA- Solid Waste Management Admistration,DPW,1,2022/01/01 05:22:13+00,2022/01/26 18:40:26+00,2022/01/20 05:22:13+00,2022/01/01 05:22:13+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,397653.87,140003.18,38.92790393,-77.02705722,231227,NaN,{D4800EAA-4890-7440-E053-792F520AC392},NaN,NaN,10050449,NaN
2,400044.359999999,143069.149999999,22-00000010,401 KENNEDY STREET NE,WASHINGTON,DC,20011,Ward 5,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2022/01/01 05:31:42+00,2022/01/04 00:22:39+00,2022/01/06 04:59:00+00,2022/01/01 05:31:42+00,NaN,NaN,NaN,Canceled,NaN,NaN,Standard,400044.36,143069.15,38.95552621,-76.99948821,28158,NaN,{D4800EAA-4891-7440-E053-792F520AC392},NaN,NaN,10050450,NaN
3,402389.289999999,139113.440000001,22-00000016,2135 QUEENS CHAPEL ROAD NE,WASHINGTON,DC,20018,Ward 5,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2022/01/01 07:04:29+00,2022/01/01 18:17:24+00,2022/01/03 07:04:29+00,2022/01/01 07:04:29+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,402389.29,139113.44,38.91988842,-76.97244812,286671,NaN,{D481BFEE-13F7-6BC3-E053-792F520A91CF},NaN,NaN,10050451,NaN
4,398585.560000002,133829.440000001,22-00000017,325 P STREET SW,WASHINGTON,DC,20024,Ward 6,S0261,Parking Enforcement,PEMA- Parking Enforcement Management Administr...,DPW,1,2022/01/01 07:17:07+00,2022/01/01 18:20:36+00,2022/01/03 07:17:06+00,2022/01/01 07:17:07+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,398585.56,133829.44,38.87229033,-77.01629961,276559,NaN,{D481BFEE-13F8-6BC3-E053-792F520A91CF},NaN,NaN,10050452,NaN

### Importing **2021** dataset for 311 complaints, then testing.

In [162]:
df_21 =  pd.read_csv("jack-data/311_2021.csv", dtype = str)
df_21.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,WARD,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,SERVICEORDERSTATUS,STATUS_CODE,PRIORITY,DETAILS,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GLOBALID,CREATED,EDITED,OBJECTID,SE_ANNO_CAD_DATA
0,398714.759999998,138519.219999999,21-00000003,214 RHODE ISLAND AVENUE NW,WASHINGTON,DC,20001,Ward 5,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2021/01/01 05:32:05+00,2021/01/06 15:34:42+00,2021/01/06 23:59:00+00,2021/01/01 05:32:05+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,398714.76,138519.22,38.91453813,-77.01481951,230050,{B7D1802E-75AA-7CDF-E053-532F520AE3B3},NaN,NaN,9591692,NaN
1,400430.109999999,131768.690000001,21-00000001,2720 MARTIN LUTHER KING JR AVENUE SE,WASHINGTON,DC,20032,Ward 8,BICYCLE,Abandoned Bicycle,SWMA- Solid Waste Management Admistration,DPW,1,2021/01/01 05:06:02+00,2021/01/01 05:07:01+00,2021/01/09 04:59:00+00,2021/01/01 05:06:02+00,NaN,NaN,NaN,Voided,NaN,Standard,NaN,400430.11,131768.69,38.8537276,-76.99504482,301360,{B7D1802E-75AB-7CDF-E053-532F520AE3B3},NaN,NaN,9591693,NaN
2,397886.219999999,142011.949999999,21-00000004,816 BUCHANAN STREET NW,WASHINGTON,DC,20011,Ward 4,S05SL,Streetlight Repair Investigation,Transportation Operations Administration,DDOT,1,2021/01/01 05:33:08+00,2021/01/05 05:55:04+00,2021/01/12 05:33:08+00,2021/01/01 05:33:08+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,397886.22,142011.95,38.94600012,-77.02438379,252336,{B7D1802E-75AD-7CDF-E053-532F520AE3B3},NaN,NaN,9591695,NaN
3,405022.700000003,134521.77,21-00000017,4237 H STREET SE,WASHINGTON,DC,20019,Ward 7,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2021/01/01 11:58:18+00,2021/01/04 12:54:36+00,2021/01/05 04:59:00+00,2021/01/01 11:58:18+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,405022.7,134521.77,38.87851424,-76.94211478,24709,{B7D764C0-4508-BB8F-E053-532F520A63E8},NaN,NaN,9591696,NaN
4,392775.280000001,142022.34,21-00000007,4216 YUMA STREET NW,WASHINGTON,DC,20016,Ward 3,S05SL,Streetlight Repair Investigation,Transportation Operations Administration,DDOT,1,2021/01/01 06:05:25+00,2021/01/26 21:40:13+00,2021/01/12 06:05:25+00,2021/01/01 06:05:25+00,NaN,NaN,NaN,Closed,NaN,Standard,NaN,392775.28,142022.34,38.94606655,-77.0833418,266186,{B7D25EBE-F302-E2F7-E053-542F520AD49B},NaN,NaN,9591903,NaN

### Importing **2020** dataset for 311 complaints, then testing.

In [163]:
df_20 =  pd.read_csv("jack-data/311_2020.csv")
df_20.head()

,X,Y,SERVICEREQUESTID,STREETADDRESS,CITY,STATE,ZIPCODE,WARD,SERVICECODE,SERVICECODEDESCRIPTION,SERVICETYPECODEDESCRIPTION,ORGANIZATIONACRONYM,SERVICECALLCOUNT,ADDDATE,RESOLUTIONDATE,SERVICEDUEDATE,SERVICEORDERDATE,INSPECTIONFLAG,INSPECTIONDATE,INSPECTORNAME,SERVICEORDERSTATUS,STATUS_CODE,DETAILS,PRIORITY,XCOORD,YCOORD,LATITUDE,LONGITUDE,MARADDRESSREPOSITORYID,GLOBALID,CREATED,EDITED,OBJECTID,SE_ANNO_CAD_DATA
0,394606.08,144893.470,20-00002992,6141 31ST PLACE NW,WASHINGTON,DC,20015.0,Ward 4,C62313,Christmas Tree Removal-Seasonal,SWMA- Solid Waste Management Administration,DPW,1,2020/01/03 14:15:00+00,2020/01/22 16:30:22+00,NaN,2020/01/03 14:15:00+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,394606.080000,144893.470000,38.971944,-77.062245,260261.0,{9B922E97-CDB6-E4E4-E053-532F520A122A},NaN,NaN,9272477,NaN
1,394380.55,137456.230,20-00009566,3270 M STREET NW,WASHINGTON,DC,20007.0,Ward 2,DMV01,DMV - Drivers License/ID Issues,Driver Vehicle Services,DMV,1,2020/01/07 15:06:11+00,2020/01/10 14:13:28+00,2020/01/10 15:06:11+00,2020/01/07 15:06:11+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,394380.550000,137456.230000,38.904945,-77.064787,279688.0,{9B922E97-CDB7-E4E4-E053-532F520A122A},NaN,NaN,9272478,NaN
2,401417.40,132047.117,20-00008507,2300 - 2329 BLOCK OF ELVANS ROAD SE,WASHINGTON,DC,20020.0,Ward 8,RPP,Residential Parking Permit Violation,PEMA- Parking Enforcement Management Administr...,DPW,1,2020/01/06 21:49:32+00,2020/01/07 01:13:39+00,2020/01/07 21:49:31+00,2020/01/06 21:49:32+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,401417.400415,132047.117247,38.856234,-76.983670,806361.0,{9B922E97-CDB9-E4E4-E053-532F520A122A},NaN,NaN,9272480,NaN
3,401203.53,136557.370,20-00001110,1362 EMERALD STREET NE,WASHINGTON,DC,20002.0,Ward 6,S0031,Bulk Collection,SWMA- Solid Waste Management Admistration,DPW,1,2020/01/02 15:19:35+00,2020/01/13 14:03:19+00,2020/01/14 04:59:00+00,2020/01/02 15:19:35+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,401203.530000,136557.370000,38.896865,-76.986126,65825.0,{9B922E97-CDBB-E4E4-E053-532F520A122A},NaN,NaN,9272642,NaN
4,406134.37,135740.410,20-00009275,5013 EAST CAPITOL STREET SE,WASHINGTON,DC,20019.0,Ward 7,SIGNMISS,Roadway Signs,Toa-Trans Sys Mnt-Signs,DDOT,1,2020/01/07 13:37:07+00,2020/02/11 17:10:33+00,2020/07/14 13:37:07+00,2020/01/07 13:37:07+00,NaN,NaN,NaN,Closed,NaN,NaN,Standard,406134.370000,135740.410000,38.889485,-76.929292,15148.0,{9B922E97-CDC1-E4E4-E053-532F520A122A},NaN,NaN,9272648,NaN

# **1: Filtering Annual Christmas Tree Removal Complaints**

## **2025**

### Identifying service code description(s) for missed Christmas tree removal.

In [164]:
codes_test_25 = df_25['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_25))

['311Force Reported Issues', 'ATEquity Pilot', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bee Treatment and Inspection (DOH)', 'Bicycle Services', 'Bulk Collection', 'Bus and Streetcar Issues', 'Bus/Rail Issues', 'Christmas Tree Removal - Missed', 'Container Removal', 'DC Dog Park Maintenance (DGS)', 'DC Government Information', 'DC How Am I Driving?', 'DC Indoor and Outdoor Pool Maintenance  (DGS)', 'DC Spray Parks (DGS)', 'DC Water - Customer Flooding', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DGS - Overflowing Recycling Can', 'DGS - Playground Repair', 'DGS Grounds Landscaping (DGS)', 'DMOI Customer Service Tracker', 'DMV - ATEquity Pilot', 'DMV - Adjudication Supervisor', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOB - Illegal Construction', 'DOB - Vacant Private Property Inspection', 'DOEE - Bag Law Tips', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - General Air Quality Concerns', 'DOEE - Report Construction Erosion Runoff', 'DPW - Reporting Electronics in Trash', 'Dead Animal Collection', 'Dockless Vehicle Parking Complaint', 'Emergency - Flooding', 'Emergency - Heating and Cooling', 'Emergency - Power Outage/Wires Down', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass Mowing Services Missed (DGS)', 'Grass and Weeds Mowing', 'Green Infrastructure Maintenance', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Fireworks', 'Illegal Poster', 'Leaf  Collection Missed', 'Lost/Stolen Compost Bin, Broken Compost Bin or Opt-Out of Curbside Composting Pilot Program', 'Missed Curbside Compost Collection', 'Neighborhood Clean-Up', 'OCTFME - Down Cable Wires', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Pothole', 'Public Space Inspection', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can-Collection', 'Rat Replacement Containers', 'Recycling - Commercial Only', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Residential Snow Removal (ServeDC)', 'Roadway Markings / Pylons', 'Roadway Repair', 'Roadway Signs', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'Sample SR', 'Sanitation Enforcement', 'Scheduled Yard Waste', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow and Ice Removal on Public Space', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Traffic Lights and Pedestrian Walk Signals', 'Traffic Safety Input', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage']

### Filtering Christmas tree removal complaints into a new dataframe.

In [165]:
trees_25 = df_25[df_25['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal - Missed']
print(trees_25)

                      X                 Y SERVICEREQUESTID  \
547    398611.560000002  138326.579999998      25-00001306
915    394865.600000001         139040.18      25-00001451
1035   400216.770000003  136678.989999998      25-00002051
1240           393687.0  144389.300000001      25-00001743
1366   396131.159999996  137748.129999999      25-00002575
...                 ...               ...              ...
67303  403166.979999997          140204.0      25-00126264
67374  395279.100000001         138025.75      25-00126559
67569  402977.810000002         140976.52      25-00126819
67597  401801.100000001  135442.699999999      25-00126857
67611  396500.289999999  141881.629999999      25-00126893

                  STREETADDRESS        CITY STATE ZIPCODE SERVICECODE  \
547             319 R STREET NW  WASHINGTON    DC   20001     C62313m
915         2211 30TH STREET NW  WASHINGTON    DC   20008     C62313m
1035        627 MORRIS PLACE NE  WASHINGTON    DC   20002     C62313m
1240   3622 PATTERSON STREET NW  WASHINGTON    DC   20015     C62313m
1366        1301 20TH STREET NW  WASHINGTON    DC   20036     C62313m
...                         ...         ...   ...     ...         ...
67303      3037 VISTA STREET NE  WASHINGTON    DC   20018     C62313m
67374        2516 EAST PLACE NW  WASHINGTON    DC   20007     C62313m
67569    3802 EASTERN AVENUE NE  WASHINGTON    DC   20018     C62313m
67597        1738 BAY STREET SE  WASHINGTON    DC   20003     C62313m
67611    1734 ALLISON STREET NW  WASHINGTON    DC   20011     C62313m

                SERVICECODEDESCRIPTION  \
547    Christmas Tree Removal - Missed
915    Christmas Tree Removal - Missed
1035   Christmas Tree Removal - Missed
1240   Christmas Tree Removal - Missed
1366   Christmas Tree Removal - Missed
...                                ...
67303  Christmas Tree Removal - Missed
67374  Christmas Tree Removal - Missed
67569  Christmas Tree Removal - Missed
67597  Christmas Tree Removal - Missed
67611  Christmas Tree Removal - Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
547    SWMA- Solid Waste Management Administration                 DPW
915    SWMA- Solid Waste Management Administration                 DPW
1035   SWMA- Solid Waste Management Administration                 DPW
1240   SWMA- Solid Waste Management Administration                 DPW
1366   SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
67303  SWMA- Solid Waste Management Administration                 DPW
67374  SWMA- Solid Waste Management Administration                 DPW
67569  SWMA- Solid Waste Management Administration                 DPW
67597  SWMA- Solid Waste Management Administration                 DPW
67611  SWMA- Solid Waste Management Administration                 DPW

      SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
547                  1  2025/01/02 15:11:13+00  2025/02/03 15:00:38+00
915                  1  2025/01/02 15:35:41+00  2025/02/17 17:30:10+00
1035                 1  2025/01/02 17:52:59+00  2025/01/31 18:27:40+00
1240                 1  2025/01/02 16:30:07+00  2025/01/31 19:18:27+00
1366                 1  2025/01/02 19:31:41+00  2025/02/24 17:29:37+00
...                ...                     ...                     ...
67303                1  2025/03/01 14:25:12+00  2025/03/05 00:10:17+00
67374                1  2025/03/01 17:21:27+00  2025/03/04 23:47:10+00
67569                1  2025/03/01 20:07:59+00  2025/03/05 00:11:19+00
67597                1  2025/03/01 20:46:46+00  2025/03/07 14:01:44+00
67611                1  2025/03/01 21:18:42+00  2025/03/06 12:00:53+00

               SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
547    2025/01/09 15:11:13+00  2025/01/02 15:11:13+00            NaN
915    2025/01/09 15:35:41+00  2025/01/02 15:35:41+00            NaN
1035   2025/01/09 17:52:59+00  2025/01/02 17:52:59+00            NaN
1240   2025/01/09 16:30:07+00  2025/01/02 16:30:07+00            NaN
1366   2025/01/09 19:31:41+00  2025/01/02 19:31:41+00            NaN
...                       ...                     ...            ...
67303  2025/03/07 14:25:12+00  2025/03/01 14:25:12+00            NaN
67374  2025/03/07 17:21:27+00  2025/03/01 17:21:27+00            NaN
67569  2025/03/07 20:07:59+00  2025/03/01 20:07:59+00            NaN
67597  2025/03/07 20:46:46+00  2025/03/01 20:46:46+00            NaN
67611  2025/03/07 21:18:42+00  2025/03/01 21:18:42+00            NaN

      INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE  PRIORITY  \
547              NaN           NaN             Closed         NaN  Standard
915              NaN           NaN             Closed         NaN  Standard
1035             NaN           NaN             Closed         NaN  Standard
1240             NaN           NaN             Closed         NaN  Standard
1366             NaN           NaN             Closed         NaN  Standard
...              ...           ...                ...         ...       ...
67303            NaN           NaN             Closed         NaN  Standard
67374            NaN           NaN             Closed         NaN  Standard
67569            NaN           NaN             Closed         NaN  Standard
67597            NaN           NaN             Closed         NaN  Standard
67611            NaN           NaN             Closed         NaN  Standard

      DETAILS    WARD     XCOORD     YCOORD     LATITUDE     LONGITUDE  \
547       NaN  Ward 5  398611.56  138326.58  38.91280261  -77.01600908
915       NaN  Ward 3   394865.6  139040.18  38.91921705  -77.05920631
1035      NaN  Ward 6  400216.77  136678.99  38.89796161  -76.99750111
1240      NaN  Ward 3     393687   144389.3  38.96739576  -77.07284631
1366      NaN  Ward 2  396131.16  137748.13  38.90758432  -77.04460548
...       ...     ...        ...        ...          ...           ...
67303     NaN  Ward 5  403166.98     140204  38.92971041  -76.96347523
67374     NaN  Ward 2   395279.1  138025.75  38.91008105  -77.05443114
67569     NaN  Ward 5  402977.81  140976.52  38.93667016  -76.96565358
67597     NaN  Ward 7   401801.1   135442.7  38.88682284  -76.97924041
67611     NaN  Ward 4  396500.29  141881.63   38.9448214   -77.0403707

      MARADDRESSREPOSITORYID                                GLOBALID CREATED  \
547                   237599  {2ABBA9F9-F053-6E9D-E063-782F520AE15C}     NaN
915                   220393  {2ABC1542-F711-5414-E063-782F520A6922}     NaN
1035                    3030  {2ABDF806-2743-518D-E063-782F520AE1E3}     NaN
1240                  263211  {2ABCEBE4-200C-76F7-E063-792F520AFF00}     NaN
1366                  226640  {2ABF6FA5-2DE4-21B6-E063-792F520A72F9}     NaN
...                      ...                                     ...     ...
67303                  41353  {2F49CBE3-1B61-7990-E063-782F520A419D}     NaN
67374                 272630  {2F4C4F90-E9B8-2F1E-E063-782F520A2345}     NaN
67569                  30700  {2F4E9DBC-ABC7-7203-E063-792F520A9CA3}     NaN
67597                  56548  {2F4F3EAF-FDBB-4D10-E063-792F520AA877}     NaN
67611                 258632  {2F4FA9F1-EF97-4175-E063-792F520A3BAD}     NaN

      EDITED  OBJECTID
547      NaN  11866176
915      NaN  11866545
1035     NaN  11866666
1240     NaN  11866871
1366     NaN  11866997
...      ...       ...
67303    NaN  11945623
67374    NaN  11945694
67569    NaN  11945889
67597    NaN  11945917
67611    NaN  11945931

[2742 rows x 33 columns]

### Counting rows in new dataframe, which reflect total Christmas tree removal complaints for **2025**.

In [166]:
count_25 = len(trees_25)
print(count_25)

2742

## **2024**

### Identifying service code description(s) for missed Christmas tree removal.

In [167]:
codes_test_24 = df_24['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_24))

['211 Warmline Service Request', '311Force Reported Issues', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bee Treatment and Inspection (DOH)', 'Bicycle Services', 'Bulk Collection', 'Bus/Rail Issues', 'Christmas Tree Removal - Missed', 'Container Removal', 'DC Dog Park Maintenance (DGS)', 'DC Government Information', 'DC How Am I Driving?', 'DC Indoor and Outdoor Pool Maintenance  (DGS)', 'DC Spray Parks (DGS)', 'DC Water - Customer Flooding', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DGS - Overflowing Recycling Can', 'DGS - Playground Repair', 'DGS Grounds Landscaping (DGS)', 'DMV - Adjudication Supervisor', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Processing Center Manager', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOB - Illegal Construction', 'DOB - Vacant Private Property Inspection', 'DOEE - Bag Law Tips', 'DOEE - Construction – Erosion Runoff', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - General Air Quality Concerns', 'DOEE - Report Construction Erosion Runoff', 'DPW - Reporting Electronics in Trash', 'Dead Animal Collection', 'Dockless Vehicle Parking Complaint', 'Emergency - Flooding', 'Emergency - Heating and Cooling', 'Emergency - Power Outage/Wires Down', 'Emergency - Senior Assistance', 'Emergency - Transportation', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass Mowing Services Missed (DGS)', 'Grass and Weeds Mowing', 'Green Infrastructure Maintenance', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Fireworks', 'Illegal Poster', 'Leaf  Collection Missed', 'Lost/Stolen Compost Bin, Broken Compost Bin or Opt-Out of Curbside Composting Pilot Program', 'Missed Curbside Compost Collection', 'Neighborhood Clean-Up', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Pothole', 'Public Space Inspection', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can-Collection', 'Rat Replacement Containers', 'Recycling - Commercial Only', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Roadway Repair', 'Roadway Signs', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'Sample SR', 'Sanitation Enforcement', 'Scheduled Yard Waste', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Ice Removal from Bridges Sidewalks', 'Snow Metro Bus', 'Snow Removal Complaints for Sidewalks', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow Towing', 'Snow and Ice Removal on Public Space', 'Snow/Ice Removal on Public Streets', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Traffic Safety Input', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Utility Repair Issue', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage']

### Filtering Christmas tree removal complaints into a new dataframe.

In [168]:
trees_24 = df_24[df_24['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal - Missed']
print(trees_24)

                X           Y SERVICEREQUESTID  \
541    400152.370  137353.140      24-00000719
643    392593.970  141944.640      24-00001022
700    395148.440  142773.220      24-00001162
737    396932.160  146739.840      24-00001241
897    398660.180  138183.630      24-00001800
...           ...         ...              ...
66533  392596.480  142670.680      24-00116687
66535  401607.060  140107.910      24-00116690
66689  393896.970  139790.710      24-00117074
67444  400930.215  135440.751      24-00118228
67709  405799.030  137092.510      24-00118289

                               STREETADDRESS        CITY STATE  ZIPCODE  \
541                       1109 6TH STREET NE  WASHINGTON    DC  20002.0
643                     4346 WINDOM PLACE NW  WASHINGTON    DC  20016.0
700               2800 CHESTERFIELD PLACE NW  WASHINGTON    DC  20008.0
737                   1465 NORTHGATE ROAD NW  WASHINGTON    DC  20012.0
897                       1610 3RD STREET NW  WASHINGTON    DC  20001.0
...                                      ...         ...   ...      ...
66533               4326 DAVENPORT STREET NW  WASHINGTON    DC  20016.0
66535                  1619 IRVING STREET NE  WASHINGTON    DC  20018.0
66689                  3528 FULTON STREET NW  WASHINGTON    DC  20007.0
67444  1200 - 1299 BLOCK OF WALTER STREET SE  WASHINGTON    DC  20003.0
67709                     4810 JAY STREET NE  WASHINGTON    DC  20019.0

         WARD SERVICECODE           SERVICECODEDESCRIPTION  \
541    Ward 6     C62313m  Christmas Tree Removal - Missed
643    Ward 3     C62313m  Christmas Tree Removal - Missed
700    Ward 3     C62313m  Christmas Tree Removal - Missed
737    Ward 4     C62313m  Christmas Tree Removal - Missed
897    Ward 5     C62313m  Christmas Tree Removal - Missed
...       ...         ...                              ...
66533  Ward 3     C62313m  Christmas Tree Removal - Missed
66535  Ward 5     C62313m  Christmas Tree Removal - Missed
66689  Ward 3     C62313m  Christmas Tree Removal - Missed
67444  Ward 6     C62313m  Christmas Tree Removal - Missed
67709  Ward 7     C62313m  Christmas Tree Removal - Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
541    SWMA- Solid Waste Management Administration                 DPW
643    SWMA- Solid Waste Management Administration                 DPW
700    SWMA- Solid Waste Management Administration                 DPW
737    SWMA- Solid Waste Management Administration                 DPW
897    SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
66533  SWMA- Solid Waste Management Administration                 DPW
66535  SWMA- Solid Waste Management Administration                 DPW
66689  SWMA- Solid Waste Management Administration                 DPW
67444  SWMA- Solid Waste Management Administration                 DPW
67709  SWMA- Solid Waste Management Administration                 DPW

       SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
541                   1  2024/01/02 14:04:56+00  2024/01/04 22:52:29+00
643                   1  2024/01/02 15:13:23+00  2024/01/04 22:51:08+00
700                   1  2024/01/02 15:49:30+00  2024/01/04 22:51:40+00
737                   1  2024/01/02 16:04:02+00  2024/01/03 22:12:04+00
897                   1  2024/01/02 18:10:29+00  2024/01/03 22:45:43+00
...                 ...                     ...                     ...
66533                 1  2024/03/02 16:37:28+00  2024/03/05 21:42:06+00
66535                 1  2024/03/02 16:42:32+00  2024/03/05 21:42:11+00
66689                 1  2024/03/02 22:20:32+00  2024/03/05 21:42:19+00
67444                 1  2024/03/04 13:23:45+00  2024/03/05 21:42:36+00
67709                 1  2024/03/04 13:40:59+00  2024/03/05 21:42:49+00

               SERVICEDUEDATE        SERVICEORDERDATE  STATUS_CODE  \
541    2024/01/09 14:04:56+00  2024/01/02 14:04:56+00          NaN
643    2024/01/09 15:13:23+00  2024/01/02 15:13:23+00          NaN
700    2024/01/09 15:49:30+00  2024/01/02 15:49:30+00          NaN
737    2024/01/09 16:04:02+00  2024/01/02 16:04:02+00          NaN
897    2024/01/09 18:10:29+00  2024/01/02 18:10:29+00          NaN
...                       ...                     ...          ...
66533  2024/03/08 16:37:28+00  2024/03/02 16:37:28+00          NaN
66535  2024/03/08 16:42:32+00  2024/03/02 16:42:32+00          NaN
66689  2024/03/08 22:20:32+00  2024/03/02 22:20:32+00          NaN
67444  2024/03/11 13:23:45+00  2024/03/04 13:23:45+00          NaN
67709  2024/03/11 13:40:59+00  2024/03/04 13:40:59+00          NaN

      SERVICEORDERSTATUS  INSPECTIONFLAG  INSPECTIONDATE  INSPECTORNAME  \
541               Closed             NaN             NaN            NaN
643               Closed             NaN             NaN            NaN
700               Closed             NaN             NaN            NaN
737               Closed             NaN             NaN            NaN
897               Closed             NaN             NaN            NaN
...                  ...             ...             ...            ...
66533             Closed             NaN             NaN            NaN
66535             Closed             NaN             NaN            NaN
66689             Closed             NaN             NaN            NaN
67444             Closed             NaN             NaN            NaN
67709             Closed             NaN             NaN            NaN

       PRIORITY DETAILS         XCOORD         YCOORD   LATITUDE  LONGITUDE  \
541    Standard     NaN  400152.370000  137353.140000  38.904035 -76.998243
643    Standard     NaN  392593.970000  141944.640000  38.945365 -77.085432
700    Standard     NaN  395148.440000  142773.220000  38.952847 -77.055971
737    Standard     NaN  396932.160000  146739.840000  38.988587 -77.035411
897    Standard     NaN  398660.180000  138183.630000  38.911515 -77.015448
...         ...     ...            ...            ...        ...        ...
66533  Standard     NaN  392596.480000  142670.680000  38.951905 -77.085411
66535  Standard     NaN  401607.060000  140107.910000  38.928849 -76.981466
66689  Standard     NaN  393896.970000  139790.710000  38.925972 -77.070383
67444  Standard     NaN  400930.215103  135440.751298  38.886806 -76.989278
67709  Standard     NaN  405799.030000  137092.510000  38.901668 -76.933146

       MARADDRESSREPOSITORYID                                GLOBALID  \
541                     74189  {0DF8296D-7972-27FE-E063-782F520AE039}
643                    265555  {0DF8FFFF-0205-453A-E063-782F520AAED1}
700                    219568  {0DF9A0EF-CB02-6D73-E063-782F520A8A31}
737                    256915  {0DF9D691-9D52-5D90-E063-782F520A4342}
897                    237647  {0DFB83BB-39FA-6C84-E063-792F520AEA28}
...                       ...                                     ...
66533                  265771  {12B1405E-6DFB-5E28-E063-792F520A8BE0}
66535                   59421  {12B1405E-6DFD-5E28-E063-792F520A8BE0}
66689                  262720  {12B6122F-ADDE-4CF6-E063-792F520A56CB}
67444                  802998  {12D6C2A3-840D-4795-E063-792F520A919E}
67709                   17376  {12D6F85A-C26C-756D-E063-782F520AF496}

       CREATED  EDITED  SE_ANNO_CAD_DATA  OBJECTID
541        NaN     NaN               NaN  11265907
643        NaN     NaN               NaN  11266009
700        NaN     NaN               NaN  11266066
737        NaN     NaN               NaN  11266103
897        NaN     NaN               NaN  11266265
...        ...     ...               ...       ...
66533      NaN     NaN               NaN  11360320
66535      NaN     NaN               NaN  11360322
66689      NaN     NaN               NaN  11360476
67444      NaN     NaN               NaN  11361343
67709      NaN     NaN               NaN  11361608

[1090 rows x 34 columns]

### Counting rows in new dataframe, which reflect total Christmas tree removal complaints for **2024**.

In [169]:
count_24 = len(trees_24)
print(count_24)

1090

## **2023**

### Identifying service code description(s) for missed Christmas tree removal.

In [170]:
codes_test_23 = df_23['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_23))

['211 Warmline Service Request', '311Force Reported Issues', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bee Treatment and Inspection (DOH)', 'Bee Treatment or Arboviral Inspection', 'Bicycle Services', 'Bulk Collection', 'Bus/Rail Issues', 'Christmas Tree Removal - Missed', 'Container Removal', 'DC Dog Park Maintenance (DGS)', 'DC Facilities Landscaping and Grounds Maintenance(DGS)', 'DC Government Information', 'DC How Am I Driving?', 'DC Indoor and Outdoor Pool Maintenance  (DGS)', 'DC Spray Parks (DGS)', 'DC Water - Customer Flooding', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DGS - Overflowing Recycling Can', 'DGS - Playground Repair', 'DGS Grounds Landscaping (DGS)', 'DMV - Adjudication Supervisor', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Processing Center Manager', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOB - Illegal Construction', 'DOB - Vacant Private Property Inspection', 'DOEE - Bag Law Tips', 'DOEE - Construction – Erosion Runoff', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - General Air Quality Concerns', 'DOEE - Reporting Electronics in Trash', 'DPW - Reporting Electronics in Trash', 'Dead Animal Collection', 'Dockless Vehicle Complaint', 'Dockless Vehicle Parking Complaint', 'Emergency - Flooding', 'Emergency - Heating and Cooling', 'Emergency - Power Outage/Wires Down', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass Mowing Services Missed', 'Grass Mowing Services Missed (DGS)', 'Grass and Weeds Mowing', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Fireworks', 'Illegal Poster', 'Leaf  Collection Missed', 'Lost/Stolen Compost Bin, Broken Compost Bin or Opt-Out of Curbside Composting Pilot Program', 'Missed Curbside Compost Collection', 'Neighborhood Clean-Up', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Pothole', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can- Installation/Removal/Repair', 'Public Space Litter Can-Collection', 'Rat Replacement Containers', 'Recycling - Commercial Only', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Roadway Repair', 'Roadway Signs', 'Roadway Signs - old', 'Roadway Signs Test', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'SalesForce DC311 Application Request', 'Sample SR', 'Sanitation Enforcement', 'Scheduled Yard Waste', 'Shut the Door (DOEE)', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Ice Removal from Bridges Sidewalks', 'Snow Metro Bus Shelter/Stop', 'Snow Other (Snow Vehicle / Property Damage)', 'Snow Removal Complaints for Sidewalks', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow Towing', 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)', 'Snow/Ice Removal on Public Streets', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Traffic Safety Input', 'Traffic Safety Investigation', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Utility Repair Issue', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage']

### Filtering Christmas tree removal complaints into a new dataframe.

In [171]:
trees_23 = df_23[df_23['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal - Missed']
print(trees_23)

               X          Y SERVICEREQUESTID            STREETADDRESS  \
1261   401077.33  136494.94      23-00001726         1318 E STREET NE
1622   401634.83  138372.61      23-00001803      1725 15TH STREET NE
1633   402397.40  136533.78      23-00001875       521 24TH STREET NE
1637   404967.50  133407.55      23-00001880      1413 42ND STREET SE
1951   396652.83  142377.38      23-00002850   4814 BLAGDEN AVENUE NW
...          ...        ...              ...                      ...
59664  394718.70  144135.20      23-00102172  2963 MCKINLEY STREET NW
59803  400753.69  135482.27      23-00102642       212 11TH STREET SE
59926  395521.89  139830.00      23-00103159    2733 WOODLEY PLACE NW
60501  403712.69  133469.79      23-00104185       1718 33RD PLACE SE
60682  405675.70  137472.28      23-00104403       1115 47TH PLACE NE

             CITY STATE  ZIPCODE    WARD SERVICECODE  \
1261   WASHINGTON    DC  20002.0  Ward 6     C62313m
1622   WASHINGTON    DC  20002.0  Ward 5     C62313m
1633   WASHINGTON    DC  20002.0  Ward 7     C62313m
1637   WASHINGTON    DC  20020.0  Ward 7     C62313m
1951   WASHINGTON    DC  20011.0  Ward 4     C62313m
...           ...   ...      ...     ...         ...
59664  WASHINGTON    DC  20015.0  Ward 4     C62313m
59803  WASHINGTON    DC  20003.0  Ward 6     C62313m
59926  WASHINGTON    DC  20008.0  Ward 3     C62313m
60501  WASHINGTON    DC  20020.0  Ward 7     C62313m
60682  WASHINGTON    DC  20019.0  Ward 7     C62313m

                SERVICECODEDESCRIPTION  \
1261   Christmas Tree Removal - Missed
1622   Christmas Tree Removal - Missed
1633   Christmas Tree Removal - Missed
1637   Christmas Tree Removal - Missed
1951   Christmas Tree Removal - Missed
...                                ...
59664  Christmas Tree Removal - Missed
59803  Christmas Tree Removal - Missed
59926  Christmas Tree Removal - Missed
60501  Christmas Tree Removal - Missed
60682  Christmas Tree Removal - Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
1261   SWMA- Solid Waste Management Administration                 DPW
1622   SWMA- Solid Waste Management Administration                 DPW
1633   SWMA- Solid Waste Management Administration                 DPW
1637   SWMA- Solid Waste Management Administration                 DPW
1951   SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
59664  SWMA- Solid Waste Management Administration                 DPW
59803  SWMA- Solid Waste Management Administration                 DPW
59926  SWMA- Solid Waste Management Administration                 DPW
60501  SWMA- Solid Waste Management Administration                 DPW
60682  SWMA- Solid Waste Management Administration                 DPW

       SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
1261                  1  2023/01/03 12:28:24+00  2023/01/05 17:20:06+00
1622                  1  2023/01/03 13:07:34+00  2023/01/03 16:06:31+00
1633                  1  2023/01/03 13:29:42+00  2023/01/05 17:21:39+00
1637                  1  2023/01/03 13:30:59+00  2023/01/05 17:20:39+00
1951                  1  2023/01/03 17:01:39+00  2023/01/05 17:18:43+00
...                 ...                     ...                     ...
59664                 1  2023/03/02 14:46:27+00  2023/03/07 15:57:15+00
59803                 1  2023/03/02 17:23:08+00  2023/03/07 15:57:21+00
59926                 1  2023/03/02 20:05:04+00  2023/03/07 15:57:27+00
60501                 1  2023/03/03 14:24:59+00  2023/03/06 17:54:26+00
60682                 1  2023/03/03 15:30:50+00  2023/03/06 17:54:43+00

               SERVICEDUEDATE        SERVICEORDERDATE  INSPECTIONFLAG  \
1261   2023/01/10 12:28:24+00  2023/01/03 12:28:24+00             NaN
1622   2023/01/10 13:07:34+00  2023/01/03 13:07:34+00             NaN
1633   2023/01/10 13:29:42+00  2023/01/03 13:29:42+00             NaN
1637   2023/01/10 13:30:59+00  2023/01/03 13:30:59+00             NaN
1951   2023/01/10 17:01:39+00  2023/01/03 17:01:39+00             NaN
...                       ...                     ...             ...
59664  2023/03/09 14:46:27+00  2023/03/02 14:46:27+00             NaN
59803  2023/03/09 17:23:08+00  2023/03/02 17:23:08+00             NaN
59926  2023/03/09 20:05:04+00  2023/03/02 20:05:04+00             NaN
60501  2023/03/10 14:24:59+00  2023/03/03 14:24:59+00             NaN
60682  2023/03/10 15:30:49+00  2023/03/03 15:30:50+00             NaN

       INSPECTIONDATE  INSPECTORNAME SERVICEORDERSTATUS  STATUS_CODE DETAILS  \
1261              NaN            NaN             Closed          NaN     NaN
1622              NaN            NaN             Closed          NaN     NaN
1633              NaN            NaN             Closed          NaN     NaN
1637              NaN            NaN             Closed          NaN     NaN
1951              NaN            NaN             Closed          NaN     NaN
...               ...            ...                ...          ...     ...
59664             NaN            NaN             Closed          NaN     NaN
59803             NaN            NaN             Closed          NaN     NaN
59926             NaN            NaN             Closed          NaN     NaN
60501             NaN            NaN             Closed          NaN     NaN
60682             NaN            NaN             Closed          NaN     NaN

       PRIORITY     XCOORD     YCOORD   LATITUDE  LONGITUDE  \
1261   Standard  401077.33  136494.94  38.896303 -76.987581
1622   Standard  401634.83  138372.61  38.913217 -76.981150
1633   Standard  402397.40  136533.78  38.896650 -76.972364
1637   Standard  404967.50  133407.55  38.868477 -76.942759
1951   Standard  396652.83  142377.38  38.949288 -77.038613
...         ...        ...        ...        ...        ...
59664  Standard  394718.70  144135.20  38.965114 -77.060939
59803  Standard  400753.69  135482.27  38.887181 -76.991313
59926  Standard  395521.89  139830.00  38.926336 -77.051644
60501  Standard  403712.69  133469.79  38.869044 -76.957218
60682  Standard  405675.70  137472.28  38.905090 -76.934565

       MARADDRESSREPOSITORYID                                GLOBALID  \
1261                    68049  {F15C43B4-1F88-685B-E053-782F520A8D19}
1622                   301201  {F15CE497-1FD7-42BB-E053-792F520A183A}
1633                    11670  {F15D4FE3-4E5A-5301-E053-792F520AA443}
1637                    64676  {F15D4FE3-4E5E-5301-E053-792F520AA443}
1951                   258766  {F1603EE7-C065-7944-E053-792F520A02F6}
...                       ...                                     ...
59664                  259893  {F5ED1EF4-A9B9-715D-E053-782F520AD785}
59803                   51519  {F5EF3764-C55C-3250-E053-782F520A87F1}
59926                  219135  {F5F18579-CBA9-3CAF-E053-782F520A12D3}
60501                   57290  {F600D179-60BD-227B-E053-782F520A93E0}
60682                   73822  {F601DDBD-17C3-0575-E053-792F520A4FC5}

       CREATED  EDITED  SE_ANNO_CAD_DATA  OBJECTID
1261       NaN     NaN               NaN  10583913
1622       NaN     NaN               NaN  10584274
1633       NaN     NaN               NaN  10584285
1637       NaN     NaN               NaN  10584289
1951       NaN     NaN               NaN  10584603
...        ...     ...               ...       ...
59664      NaN     NaN               NaN  10700823
59803      NaN     NaN               NaN  10700962
59926      NaN     NaN               NaN  10701085
60501      NaN     NaN               NaN  10702156
60682      NaN     NaN               NaN  10702337

[588 rows x 34 columns]

### Counting rows in new dataframe, which reflect total Christmas tree removal complaints for **2023**.

In [172]:
count_23 = len(trees_23)
print(count_23)

588

## **2022**

### Identifying service code description(s) for missed Christmas tree removal.

In [173]:
codes_test_22 = df_22['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_22))

['311Force Reported Issues', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bee Treatment or Arboviral Inspection', 'Bicycle Services', 'Bulk Collection', 'Bus/Rail Issues', 'Christmas Tree Removal - Missed', 'Christmas Tree Removal-Missed', 'Container Removal', 'Coronavirus (COVID-19) Mask & Vax Complaints', 'Coronavirus (COVID-19) Mass Gathering Tracking', 'Coronavirus (COVID-19) Tracking', 'DC Dog Park Maintenance (DGS)', 'DC Facilities Landscaping and Grounds Maintenance(DGS)', 'DC Government Information', 'DC How Am I Driving?', 'DC Indoor and Outdoor Pool Maintenance  (DGS)', 'DC Spray Parks (DGS)', 'DC Water - Customer Flooding', 'DCRA - Illegal Construction', 'DCRA - Vacant Private Property Inspection', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Processing Center Manager', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOB - Illegal Construction', 'DOB - Vacant Private Property Inspection', 'DOEE - Bag Law Tips', 'DOEE - Construction – Erosion Runoff', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - General Air Quality Concerns', 'DOEE - Reporting Electronics in Trash', 'Dead Animal Collection', 'Dockless Vehicle Complaint', 'Emergency - Flooding', 'Emergency - Power Outage/Wires Down', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass and Weeds Mowing', 'How Is My Driving - Complaint', 'How Is My Driving - Compliment', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Fireworks', 'Illegal Poster', 'Insect Treatment', 'Leaf  Collection Missed', 'Leaf Season Collection', 'Neighborhood Clean-Up', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Pothole', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can- Installation/Removal/Repair', 'Public Space Litter Can-Collection', 'Rat Replacement Containers', 'Recycling - Commercial Only', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Roadway Repair', 'Roadway Signs', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'Sample SR', 'Sanitation Enforcement', 'Scheduled Yard Waste', 'Shut the Door (DOEE)', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Metro Bus Shelter/Stop', 'Snow Other (Snow Vehicle / Property Damage)', 'Snow Removal Complaints for Sidewalks', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow Towing', 'Snow/Ice Removal', 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)', 'Snow/Ice Removal on Public Streets', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Ticket Ombudsman', 'Traffic Safety Investigation', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Utility Repair Issue', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage']

### Filtering Christmas tree removal complaints into new dataframe.

In [174]:
trees_22 = df_22[df_22['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal - Missed']
print(trees_22)

                       X                 Y SERVICEREQUESTID  \
384587  400430.109999999  131768.690000001      22-00617655

                               STREETADDRESS        CITY STATE ZIPCODE  \
384587  2720 MARTIN LUTHER KING JR AVENUE SE  WASHINGTON    DC   20032

          WARD SERVICECODE           SERVICECODEDESCRIPTION  \
384587  Ward 8     C62313m  Christmas Tree Removal - Missed

                         SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
384587  SWMA- Solid Waste Management Administration                 DPW

       SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
384587                1  2022/12/30 19:01:54+00  2022/12/30 19:24:21+00

                SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
384587  2023/01/09 19:01:54+00  2022/12/30 19:01:54+00            NaN

       INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE DETAILS  \
384587            NaN           NaN             Closed         NaN     NaN

        PRIORITY     XCOORD     YCOORD    LATITUDE     LONGITUDE  \
384587  Standard  400430.11  131768.69  38.8537276  -76.99504482

       MARADDRESSREPOSITORYID GIS_ID                                GLOBALID  \
384587                 301360    NaN  {F11174B8-3877-0EE3-E053-792F520A7372}

       CREATED EDITED  OBJECTID SE_ANNO_CAD_DATA
384587     NaN    NaN  10577407              NaN

In [175]:
trees_22_alt = df_22[df_22['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal-Missed']
print(trees_22_alt)

                      X                 Y SERVICEREQUESTID  \
16298  401698.939999998  132068.079999998      22-00025139
16580  400657.270000003  129146.550000001      22-00026374
16637  391428.240000002  139896.760000002      22-00026439
17282         404224.43         133553.32      22-00026620
17845  401521.060000002         134977.07      22-00027433
...                 ...               ...              ...
56121  401908.159999996  136344.329999998      22-00093246
56167  398198.780000001  138015.710000001      22-00093141
56260         397695.82  141741.710000001      22-00093814
56261  400957.799999997  135898.870000001      22-00093816
56372  396523.969999999  138059.219999999      22-00093998

                               STREETADDRESS        CITY STATE ZIPCODE  \
16298               1706 FRANKFORD STREET SE  WASHINGTON    DC   20020
16580                       820 H R DRIVE SE  WASHINGTON    DC   20032
16637             2818 UNIVERSITY TERRACE NW  WASHINGTON    DC   20016
17282               3721 CARPENTER STREET SE  WASHINGTON    DC   20020
17845                       1539 E STREET SE  WASHINGTON    DC   20003
...                                      ...         ...   ...     ...
56121                       1828 D STREET NE  WASHINGTON    DC   20002
56167                  1507 MARION STREET NW  WASHINGTON    DC   20001
56260                    4321 IOWA AVENUE NW  WASHINGTON    DC   20011
56261                123 TENNESSEE AVENUE NE  WASHINGTON    DC   20002
56372  1700 - 1799 BLOCK OF CHURCH STREET NW  WASHINGTON    DC   20036

         WARD SERVICECODE         SERVICECODEDESCRIPTION  \
16298  Ward 8     C62313m  Christmas Tree Removal-Missed
16580  Ward 8     C62313m  Christmas Tree Removal-Missed
16637  Ward 3     C62313m  Christmas Tree Removal-Missed
17282  Ward 7     C62313m  Christmas Tree Removal-Missed
17845  Ward 6     C62313m  Christmas Tree Removal-Missed
...       ...         ...                            ...
56121  Ward 6     C62313m  Christmas Tree Removal-Missed
56167  Ward 6     C62313m  Christmas Tree Removal-Missed
56260  Ward 4     C62313m  Christmas Tree Removal-Missed
56261  Ward 6     C62313m  Christmas Tree Removal-Missed
56372  Ward 2     C62313m  Christmas Tree Removal-Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
16298  SWMA- Solid Waste Management Administration                 DPW
16580  SWMA- Solid Waste Management Administration                 DPW
16637  SWMA- Solid Waste Management Administration                 DPW
17282  SWMA- Solid Waste Management Administration                 DPW
17845  SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
56121  SWMA- Solid Waste Management Administration                 DPW
56167  SWMA- Solid Waste Management Administration                 DPW
56260  SWMA- Solid Waste Management Administration                 DPW
56261  SWMA- Solid Waste Management Administration                 DPW
56372  SWMA- Solid Waste Management Administration                 DPW

      SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
16298                1  2022/01/14 16:48:46+00  2022/01/19 21:27:59+00
16580                1  2022/01/15 16:22:42+00  2022/01/19 22:11:21+00
16637                1  2022/01/15 17:50:53+00  2022/01/19 21:33:20+00
17282                1  2022/01/15 21:33:51+00  2022/01/19 21:32:29+00
17845                1  2022/01/17 16:10:00+00  2022/01/19 21:30:36+00
...                ...                     ...                     ...
56121                1  2022/02/28 18:45:44+00  2022/03/03 19:50:24+00
56167                1  2022/02/28 18:12:12+00  2022/03/03 20:43:26+00
56260                1  2022/02/28 20:34:31+00  2022/03/03 20:43:31+00
56261                1  2022/02/28 20:34:46+00  2022/03/03 19:50:29+00
56372                1  2022/02/28 21:28:36+00  2022/03/03 20:43:35+00

               SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
16298  2022/01/24 16:48:46+00  2022/01/14 16:48:46+00            NaN
16580  2022/01/24 16:22:42+00  2022/01/15 16:22:42+00            NaN
16637  2022/01/24 17:50:52+00  2022/01/15 17:50:53+00            NaN
17282  2022/01/24 21:33:51+00  2022/01/15 21:33:51+00            NaN
17845  2022/01/24 16:09:59+00  2022/01/17 16:10:00+00            NaN
...                       ...                     ...            ...
56121  2022/03/07 18:45:44+00  2022/02/28 18:45:44+00            NaN
56167  2022/03/07 18:12:12+00  2022/02/28 18:12:12+00            NaN
56260  2022/03/07 20:34:31+00  2022/02/28 20:34:31+00            NaN
56261  2022/03/07 20:34:46+00  2022/02/28 20:34:46+00            NaN
56372  2022/03/07 21:28:36+00  2022/02/28 21:28:36+00            NaN

      INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE DETAILS  \
16298            NaN           NaN             Closed         NaN     NaN
16580            NaN           NaN             Closed         NaN     NaN
16637            NaN           NaN             Closed         NaN     NaN
17282            NaN           NaN             Closed         NaN     NaN
17845            NaN           NaN             Closed         NaN     NaN
...              ...           ...                ...         ...     ...
56121            NaN           NaN             Closed         NaN     NaN
56167            NaN           NaN             Closed         NaN     NaN
56260            NaN           NaN             Closed         NaN     NaN
56261            NaN           NaN             Closed         NaN     NaN
56372            NaN           NaN             Closed         NaN     NaN

       PRIORITY     XCOORD         YCOORD     LATITUDE     LONGITUDE  \
16298  Standard  401698.94      132068.08   38.8564231  -76.98042625
16580  Standard  400657.27      129146.55  38.83010605  -76.99243028
16637  Standard  391428.24      139896.76  38.92690626  -77.09885421
17282  Standard  404224.43      133553.32  38.86979426  -76.95132057
17845  Standard  401521.06      134977.07  38.88262879   -76.9824692
...         ...        ...            ...          ...           ...
56121  Standard  401908.16      136344.33  38.89494483  -76.97800392
56167  Standard  398198.78      138015.71  38.91000144  -77.02076772
56260  Standard  397695.82      141741.71  38.94356524  -77.02657926
56261  Standard   400957.8      135898.87  38.89093351   -76.9889597
56372  Standard  396523.97  138059.220007  38.91038803  -77.04007818

      MARADDRESSREPOSITORYID GIS_ID                                GLOBALID  \
16298                  57742    NaN  {D5A34E81-4B07-47D2-E053-792F520A018B}
16580                 278624    NaN  {D5A3B743-C2F1-7A8D-E053-792F520AF31C}
16637                 268411    NaN  {D5A3B743-C32A-7A8D-E053-792F520AF31C}
17282                  31381    NaN  {D5A71166-D124-226D-E053-792F520A3949}
17845                  60806    NaN  {D5CB1F5D-670B-6F6B-E053-792F520AE35F}
...                      ...    ...                                     ...
56121                  55251    NaN  {D919AE41-0958-5DCC-E053-782F520A8141}
56167                 238596    NaN  {D919AE41-0986-5DCC-E053-782F520A8141}
56260                 252615    NaN  {D91B5B86-E071-51A4-E053-782F520AB2CD}
56261                  70527    NaN  {D91B5B86-E072-51A4-E053-782F520AB2CD}
56372                 802630    NaN  {D91C328E-E7E1-0806-E053-782F520AE2B0}

      CREATED EDITED  OBJECTID SE_ANNO_CAD_DATA
16298     NaN    NaN  10070163              NaN
16580     NaN    NaN  10070445              NaN
16637     NaN    NaN  10070502              NaN
17282     NaN    NaN  10071147              NaN
17845     NaN    NaN  10071998              NaN
...       ...    ...       ...              ...
56121     NaN    NaN  10122920              NaN
56167     NaN    NaN  10122966              NaN
56260     NaN    NaN  10123059              NaN
56261     NaN    NaN  10123060              NaN
56372     NaN    NaN  10123171              NaN

[1308 rows x 35 columns]

### Counting rows in new dataframes, which reflect total Christmas tree removal complaints for **2022**.

In [176]:
count_22 = (len(trees_22) + len(trees_22_alt))
print(count_22)

1309

## **2021**

### Identifying service code description(s) for missed Christmas tree removal.

In [177]:
codes_test_21 = df_21['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_21))

['311Force Reported Issues', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bicycle Services', 'Bulk Collection', 'Bus/Rail Issues', 'Christmas Tree Removal-Missed', 'Container Removal', 'Coronavirus (COVID-19) Mass Gathering Tracking', 'Coronavirus (COVID-19) Tracking', 'DC Facilities Landscaping and Grounds Maintenance(DGS)', 'DC Government Information', 'DC Water - Customer Flooding', 'DCRA - Illegal Construction', 'DCRA - Vacant Private Property Inspection', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DMV - Adjudication Supervisor', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Processing Center Manager', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOEE - Bag Law Tips', 'DOEE - Construction – Erosion Runoff', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - General Air Quality Concerns', 'DOEE - Nuisance Odor Complaints', 'DOEE - Reporting Electronics in Trash', 'Dead Animal Collection', 'Emergency - Power Outage/Wires Down', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass and Weeds Mowing', 'How Is My Driving - Complaint', 'How Is My Driving - Compliment', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Poster', 'Insect Treatment', 'Issue', 'Leaf Season Collection', 'Neighborhood Clean-Up', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Playground Maintenance', 'Pothole', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can- Installation/Removal/Repair', 'Public Space Litter Can-Collection', 'Quarantine Resource and Service Request (COVID-19)', 'Rat Replacement Containers', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Roadway Repair', 'Roadway Signs', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'Sample SR', 'Sanitation Enforcement', 'Scheduled Yard Waste', 'Shut the Door (DOEE)', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Metro Bus Shelter/Stop', 'Snow Other (Snow Vehicle / Property Damage)', 'Snow Removal Complaints for Sidewalks', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow Towing', 'Snow/Ice Removal', 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Test-SW-Bulk Scheduled', 'Traffic Safety Investigation', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Utility Repair Issue', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage', 'Yard Waste - Missed']

### Filtering Christmas tree removal complaints into new dataframes.

In [178]:
trees_21 = df_21[df_21['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal-Missed']
print(trees_21)

                      X                 Y SERVICEREQUESTID  \
6289   398406.219999999         140235.77      21-00010708
6407   396473.909999996         139758.59      21-00011026
6414   393973.810000002  143368.170000002      21-00010918
6472   398967.079999998  137756.289999999      21-00011456
6473   401052.960000001  137507.120000001      21-00011448
...                 ...               ...              ...
41698  398192.909999996  141568.390000001      21-00070160
42024  397685.740000002  137496.390000001      21-00070855
42089  391927.859999999  138901.350000001      21-00071032
42096  395361.259999998         141541.34      21-00071036
42145  396745.369999997  146281.370000001      21-00071077

                              STREETADDRESS        CITY STATE ZIPCODE    WARD  \
6289                     3112 PARK PLACE NW  WASHINGTON    DC   20010  Ward 1
6407                   1729 LANIER PLACE NW  WASHINGTON    DC   20009  Ward 1
6414                  3616 INGOMAR PLACE NW  WASHINGTON    DC   20015  Ward 3
6472                     1307 1ST STREET NW  WASHINGTON    DC   20001  Ward 5
6473                   1206 OATES STREET NE  WASHINGTON    DC   20002  Ward 5
...                                     ...         ...   ...     ...     ...
41698  600  - 699 BLOCK OF UPSHUR STREET NW  WASHINGTON    DC   20011  Ward 4
42024                   1125 11TH STREET NW  WASHINGTON    DC   20001  Ward 2
42089              4727 BERKELEY TERRACE NW  WASHINGTON    DC   20007  Ward 3
42096                  2604 TILDEN PLACE NW  WASHINGTON    DC   20008  Ward 3
42145                1619 JONQUIL STREET NW  WASHINGTON    DC   20012  Ward 4

      SERVICECODE         SERVICECODEDESCRIPTION  \
6289      C62313m  Christmas Tree Removal-Missed
6407      C62313m  Christmas Tree Removal-Missed
6414      C62313m  Christmas Tree Removal-Missed
6472      C62313m  Christmas Tree Removal-Missed
6473      C62313m  Christmas Tree Removal-Missed
...           ...                            ...
41698     C62313m  Christmas Tree Removal-Missed
42024     C62313m  Christmas Tree Removal-Missed
42089     C62313m  Christmas Tree Removal-Missed
42096     C62313m  Christmas Tree Removal-Missed
42145     C62313m  Christmas Tree Removal-Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
6289   SWMA- Solid Waste Management Administration                 DPW
6407   SWMA- Solid Waste Management Administration                 DPW
6414   SWMA- Solid Waste Management Administration                 DPW
6472   SWMA- Solid Waste Management Administration                 DPW
6473   SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
41698  SWMA- Solid Waste Management Administration                 DPW
42024  SWMA- Solid Waste Management Administration                 DPW
42089  SWMA- Solid Waste Management Administration                 DPW
42096  SWMA- Solid Waste Management Administration                 DPW
42145  SWMA- Solid Waste Management Administration                 DPW

      SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
6289                 1  2021/01/11 15:36:21+00  2021/02/09 15:02:22+00
6407                 1  2021/01/11 17:41:35+00  2021/02/09 15:03:15+00
6414                 1  2021/01/11 16:55:12+00  2021/02/08 16:45:57+00
6472                 1  2021/01/11 19:59:16+00  2021/02/19 17:57:49+00
6473                 1  2021/01/11 19:57:41+00  2021/01/28 19:07:22+00
...                ...                     ...                     ...
41698                1  2021/02/26 20:04:47+00  2021/03/05 14:10:07+00
42024                1  2021/02/27 18:29:34+00  2021/03/05 13:14:39+00
42089                1  2021/02/27 22:15:01+00  2021/04/12 12:06:12+00
42096                1  2021/02/27 22:20:05+00  2021/04/12 12:00:10+00
42145                1  2021/02/27 22:57:15+00  2021/03/05 13:10:08+00

               SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
6289   2021/01/19 15:36:21+00  2021/01/11 15:36:21+00            NaN
6407   2021/01/19 17:41:35+00  2021/01/11 17:41:35+00            NaN
6414   2021/01/19 16:55:12+00  2021/01/11 16:55:12+00            NaN
6472   2021/01/19 19:59:16+00  2021/01/11 19:59:16+00            NaN
6473   2021/01/19 19:57:41+00  2021/01/11 19:57:41+00            NaN
...                       ...                     ...            ...
41698  2021/03/05 20:04:47+00  2021/02/26 20:04:47+00            NaN
42024  2021/03/05 18:29:34+00  2021/02/27 18:29:34+00            NaN
42089  2021/03/05 22:15:01+00  2021/02/27 22:15:01+00            NaN
42096  2021/03/05 22:20:05+00  2021/02/27 22:20:05+00            NaN
42145  2021/03/05 22:57:15+00  2021/02/27 22:57:15+00            NaN

      INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE  PRIORITY  \
6289             NaN           NaN             Closed         NaN  Standard
6407             NaN           NaN             Closed         NaN  Standard
6414             NaN           NaN             Closed         NaN  Standard
6472             NaN           NaN             Closed         NaN  Standard
6473             NaN           NaN             Closed         NaN  Standard
...              ...           ...                ...         ...       ...
41698            NaN           NaN             Closed         NaN  Standard
42024            NaN           NaN             Closed         NaN  Standard
42089            NaN           NaN             Closed         NaN  Standard
42096            NaN           NaN             Closed         NaN  Standard
42145            NaN           NaN             Closed         NaN  Standard

      DETAILS           XCOORD         YCOORD     LATITUDE     LONGITUDE  \
6289      NaN        398406.22      140235.77  38.93000086  -77.01838113
6407      NaN        396473.91      139758.59  38.92569665   -77.0406641
6414      NaN        393973.81      143368.17  38.95819918  -77.06952781
6472      NaN        398967.08      137756.29  38.90766573  -77.01190898
6473      NaN        401052.96      137507.12  38.90542076  -76.98786035
...       ...              ...            ...          ...           ...
41698     NaN  398192.90999999  141568.390007  38.94200475  -77.02084476
42024     NaN        397685.74      137496.39  38.90532169  -77.02668123
42089     NaN        391927.86      138901.35  38.91794435  -77.09308062
42096     NaN        395361.26      141541.34  38.94175102  -77.05350761
42145     NaN        396745.37      146281.37  38.98445662  -77.03756448

      MARADDRESSREPOSITORYID                                GLOBALID CREATED  \
6289                  229319  {B8A31011-58CF-5B4B-E053-532F520A58B1}     NaN
6407                  235986  {B8A4BE53-12D0-8A71-E053-532F520AB478}     NaN
6414                  262821  {B8A4BE53-12D7-8A71-E053-532F520AB478}     NaN
6472                  237002  {B8A73F61-6011-A7B2-E053-532F520ABE18}     NaN
6473                  285921  {B8A73F61-6012-A7B2-E053-532F520ABE18}     NaN
...                      ...                                     ...     ...
41698                 810625  {BC449FE8-E81E-4C25-E053-542F520A2746}     NaN
42024                 303363  {BC570F66-3513-89B4-E053-532F520AAE95}     NaN
42089                 224731  {BC5A667A-6505-8449-E053-532F520A8734}     NaN
42096                 219422  {BC5A667A-650C-8449-E053-532F520A8734}     NaN
42145                 256416  {BC5B3D1F-181D-93ED-E053-532F520A171F}     NaN

      EDITED OBJECTID SE_ANNO_CAD_DATA
6289     NaN  9598191              NaN
6407     NaN  9598309              NaN
6414     NaN  9598316              NaN
6472     NaN  9598374              NaN
6473     NaN  9598375              NaN
...      ...      ...              ...
41698    NaN  9636122              NaN
42024    NaN  9636976              NaN
42089    NaN  9637041              NaN
42096    NaN  9637048              NaN
42145    NaN  9637097              NaN

[673 rows x 34 columns]

### Counting rows in new dataframes, which reflect total Christmas tree removal complaints for **2021**.

In [179]:
count_21 = len(trees_21)
print(count_21)

673

## **2020**

### Identifying service code description(s) for missed Christmas tree removal.

In [180]:
codes_test_20 = df_20['SERVICECODEDESCRIPTION'].unique()
print(sorted(codes_test_20))

['311Force Reported Issues', 'Abandoned Bicycle', 'Abandoned Vehicle - On Private Property', 'Abandoned Vehicle - On Public Property', 'Alley Cleaning', 'Alley Repair', 'Bicycle Services', 'Bulk Collection', 'Bus/Rail Issues', 'Christmas Tree Collection Concerns', 'Christmas Tree Removal-Missed', 'Christmas Tree Removal-Seasonal', 'Container Removal', 'Coronavirus (COVID-19) Mass Gathering Tracking', 'Coronavirus (COVID-19) Tracking', 'DC Facilities Landscaping and Grounds Maintenance(DGS)', 'DC Government Information', 'DCRA - Illegal Construction', 'DCRA - Vacant Private Property Inspection', 'DFHV - For Hire Vehicle Concerns', 'DFHV - Lost and Found Claims (DC Taxi)', 'DMV - Adjudication Supervisor', 'DMV - Appeal', 'DMV - Copy of Ticket', 'DMV - Driver Record Issues', 'DMV - Driver and Vehicle Services Refund', 'DMV - Drivers License/ID Issues', 'DMV - Drivers License/ID Reinstatement', 'DMV - Forms, Applications, and Manuals Request', 'DMV - Hearings', 'DMV - Online Processing Issues', 'DMV - Processing Center Manager', 'DMV - Refunds - Tickets', 'DMV - Ticket Payment Dispute', 'DMV - Vehicle Inspection Issues', 'DMV - Vehicle Insurance Lapse', 'DMV - Vehicle Registration Issues', 'DMV - Vehicle Title Issues', 'DMV - eTIMS Ticket Alert Services Issues', 'DOEE - Bag Law Tips', 'DOEE - Construction – Erosion Runoff', 'DOEE - Engine Idling Tips', 'DOEE - Foam Ban / Food Service Ware Requirements', 'DOEE - Nuisance Odor Complaints', 'DOEE - Reporting Electronics in Trash', 'Dead Animal Collection', 'Emergency - Flooding', 'Emergency - Power Outage/Wires Down', 'Emergency - Senior Assistance', 'Emergency No-Parking Verification', 'FEMS - Community Events', 'FEMS - Fire Safety Education', 'FEMS - Fire Safety Inspection', 'FEMS - Smoke Alarm Application', 'Graffiti Removal', 'Grass and Weeds Mowing', 'How Is My Driving - Complaint', 'How Is My Driving - Compliment', 'Hypothermia Shelter Information', 'Illegal Dumping', 'Illegal Fireworks', 'Illegal Poster', 'Insect Treatment', 'Issue', 'Leaf Season Collection', 'Neighborhood Clean-Up', 'Out of State Parking Violation (ROSA)', 'Parking Enforcement', 'Parking Meter Repair', 'Pet Waste Complaint', 'Playground Maintenance', 'Pothole', 'Public Space Litter Can Installation', 'Public Space Litter Can Removal', 'Public Space Litter Can Repair', 'Public Space Litter Can- Installation/Removal/Repair', 'Public Space Litter Can-Collection', 'Quarantine Resource and Service Request (COVID-19)', 'Rat Replacement Containers', 'Recycling - Commercial Only', 'Recycling - School Program', 'Recycling Cart - Repair', 'Recycling Cart Delivery', 'Recycling Collection - Missed', 'Recycling- Information Request', 'Resident Parking Permit', 'Residential Parking Permit Violation', 'Roadway Repair', 'Roadway Signs', 'Roadway Striping / Markings', 'Rodent Inspection and Treatment', 'Sample SR', 'Sanitation Enforcement', 'Sidewalk Repair', 'Signed Street Sweeping Missed', 'Snow Metro Bus Shelter/Stop', 'Snow Other (Snow Vehicle / Property Damage)', 'Snow Removal Complaints for Sidewalks', 'Snow Sidewalk Shoveling Enforcement Exemption', 'Snow Ticket Reimbursement', 'Snow Towing', 'Snow/Ice Removal', 'Snow/Ice Removal (Roadways AND Bridge walkways ONLY)', 'Street Cleaning', 'Streetlight Repair Investigation', 'Supercan - Delivery', 'Supercan - Repair', 'Test', 'Test Animal - Vaccination Investigation - DAS', 'Test-Provar-Service-Question', 'Test-SW-Bulk Scheduled', 'Ticket Ombudsman', 'Traffic Safety Investigation', 'Traffic Signal Issue', 'Trash Cart - Delivery', 'Trash Cart Repair', 'Trash Collection - Missed', 'Tree Inspection', 'Tree Planting', 'Tree Pruning', 'Tree Removal', 'Utility Repair Issue', 'Vacant Lot - Public Property Only', 'Wire Down/Power Outage', 'Yard Waste - Missed']

### Filtering Christmas tree removal complaints into new dataframes.

In [181]:
trees_20 = df_20[df_20['SERVICECODEDESCRIPTION'] == 'Christmas Tree Removal-Missed']
print(trees_20)

               X          Y SERVICEREQUESTID  \
35150  400430.11  131768.69      20-00045158
35801  400562.09  135863.60      20-00046011
36108  396609.13  140452.34      20-00045638
36225  401634.83  138372.61      20-00045820
36257  397357.44  146454.19      20-00045765
...          ...        ...              ...
61724  399729.95  138406.89      20-00079895
66233  395291.46  142376.85      20-00086428
68071  399057.13  144448.20      20-00088592
71290  394392.36  145307.84      20-00094556
72514  398939.34  142854.05      20-00096297

                              STREETADDRESS        CITY STATE  ZIPCODE  \
35150  2720 MARTIN LUTHER KING JR AVENUE SE  WASHINGTON    DC  20032.0
35801                      23 9TH STREET NE  WASHINGTON    DC  20002.0
36108                   3208 17TH STREET NW  WASHINGTON    DC  20010.0
36225                   1725 15TH STREET NE  WASHINGTON    DC  20002.0
36257                  1323 FERNWAY ROAD NW  WASHINGTON    DC  20012.0
...                                     ...         ...   ...      ...
61724                 204 RANDOLPH PLACE NE  WASHINGTON    DC  20002.0
66233                   4525 28TH STREET NW  WASHINGTON    DC  20008.0
68071                69 TUCKERMAN STREET NW  WASHINGTON    DC  20011.0
71290            3286 WORTHINGTON STREET NW  WASHINGTON    DC  20015.0
72514                113 HAMILTON STREET NW  WASHINGTON    DC  20011.0

         WARD SERVICECODE         SERVICECODEDESCRIPTION  \
35150  Ward 8     C62313m  Christmas Tree Removal-Missed
35801  Ward 6     C62313m  Christmas Tree Removal-Missed
36108  Ward 1     C62313m  Christmas Tree Removal-Missed
36225  Ward 5     C62313m  Christmas Tree Removal-Missed
36257  Ward 4     C62313m  Christmas Tree Removal-Missed
...       ...         ...                            ...
61724  Ward 5     C62313m  Christmas Tree Removal-Missed
66233  Ward 3     C62313m  Christmas Tree Removal-Missed
68071  Ward 4     C62313m  Christmas Tree Removal-Missed
71290  Ward 4     C62313m  Christmas Tree Removal-Missed
72514  Ward 4     C62313m  Christmas Tree Removal-Missed

                        SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
35150  SWMA- Solid Waste Management Administration                 DPW
35801  SWMA- Solid Waste Management Administration                 DPW
36108  SWMA- Solid Waste Management Administration                 DPW
36225  SWMA- Solid Waste Management Administration                 DPW
36257  SWMA- Solid Waste Management Administration                 DPW
...                                            ...                 ...
61724  SWMA- Solid Waste Management Administration                 DPW
66233  SWMA- Solid Waste Management Administration                 DPW
68071  SWMA- Solid Waste Management Administration                 DPW
71290  SWMA- Solid Waste Management Administration                 DPW
72514  SWMA- Solid Waste Management Administration                 DPW

       SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
35150                 1  2020/02/03 21:32:26+00  2020/02/05 16:34:35+00
35801                 1  2020/02/04 16:06:35+00  2020/02/05 19:55:02+00
36108                 1  2020/02/04 12:46:35+00  2020/02/07 13:14:21+00
36225                 1  2020/02/04 14:35:40+00  2020/02/04 16:12:19+00
36257                 1  2020/02/04 14:07:06+00  2020/02/07 13:15:31+00
...                 ...                     ...                     ...
61724                 1  2020/03/04 15:25:51+00                     NaN
66233                 1  2020/03/10 13:34:41+00                     NaN
68071                 1  2020/03/11 16:59:14+00                     NaN
71290                 1  2020/03/16 16:52:04+00                     NaN
72514                 1  2020/03/17 15:24:44+00                     NaN

               SERVICEDUEDATE        SERVICEORDERDATE  INSPECTIONFLAG  \
35150                     NaN  2020/02/03 21:32:26+00             NaN
35801                     NaN  2020/02/04 16:06:35+00             NaN
36108  2020/02/11 12:46:34+00  2020/02/04 12:46:35+00             NaN
36225                     NaN  2020/02/04 14:35:40+00             NaN
36257  2020/02/11 14:07:06+00  2020/02/04 14:07:06+00             NaN
...                       ...                     ...             ...
61724  2020/03/11 15:25:51+00  2020/03/04 15:25:51+00             NaN
66233  2020/03/17 13:34:41+00  2020/03/10 13:34:41+00             NaN
68071  2020/03/18 16:59:14+00  2020/03/11 16:59:14+00             NaN
71290  2020/03/23 16:52:03+00  2020/03/16 16:52:04+00             NaN
72514  2020/03/24 15:24:44+00  2020/03/17 15:24:44+00             NaN

       INSPECTIONDATE  INSPECTORNAME SERVICEORDERSTATUS  STATUS_CODE DETAILS  \
35150             NaN            NaN             Closed          NaN     NaN
35801             NaN            NaN             Closed          NaN     NaN
36108             NaN            NaN             Closed          NaN     NaN
36225             NaN            NaN             Closed          NaN     NaN
36257             NaN            NaN             Closed          NaN     NaN
...               ...            ...                ...          ...     ...
61724             NaN            NaN               Open          NaN     NaN
66233             NaN            NaN               Open          NaN     NaN
68071             NaN            NaN               Open          NaN     NaN
71290             NaN            NaN               Open          NaN     NaN
72514             NaN            NaN               Open          NaN     NaN

       PRIORITY     XCOORD     YCOORD   LATITUDE  LONGITUDE  \
35150  Standard  400430.11  131768.69  38.853728 -76.995045
35801  Standard  400562.09  135863.60  38.890616 -76.993521
36108  Standard  396609.13  140452.34  38.931947 -77.039108
36225  Standard  401634.83  138372.61  38.913217 -76.981150
36257  Standard  397357.44  146454.19  38.986015 -77.030501
...         ...        ...        ...        ...        ...
61724  Standard  399729.95  138406.89  38.913527 -77.003114
66233  Standard  395291.46  142376.85  38.949277 -77.054318
68071  Standard  399057.13  144448.20  38.967949 -77.010880
71290  Standard  394392.36  145307.84  38.975675 -77.064715
72514  Standard  398939.34  142854.05  38.953588 -77.012237

       MARADDRESSREPOSITORYID                                GLOBALID  \
35150                301360.0  {9DB410BA-7F5B-D867-E053-532F520A1EB3}
35801                 49101.0  {9DC3FE52-3380-B37C-E053-542F520AF94D}
36108                233511.0  {9DC0A38E-00ED-3F47-E053-532F520A2B87}
36225                301201.0  {9DC250F0-85EE-DA86-E053-532F520A5668}
36257                257128.0  {9DC250F0-860E-DA86-E053-532F520A5668}
...                       ...                                     ...
61724                 52385.0  {A00A8BB4-3DA4-E559-E053-542F520A3285}
66233                219452.0  {A0891B18-5436-8AAB-E053-532F520A3F60}
68071                245483.0  {A0990710-794E-0E4E-E053-532F520A21FE}
71290                260846.0  {A0FCC565-D863-1ACE-E053-532F520A3092}
72514                246035.0  {A1100CC8-14AD-E5EA-E053-532F520A8F7B}

       CREATED  EDITED  OBJECTID  SE_ANNO_CAD_DATA
35150      NaN     NaN   9314724               NaN
35801      NaN     NaN   9315375               NaN
36108      NaN     NaN   9315682               NaN
36225      NaN     NaN   9315799               NaN
36257      NaN     NaN   9315831               NaN
...        ...     ...       ...               ...
61724      NaN     NaN   9341319               NaN
66233      NaN     NaN   9345828               NaN
68071      NaN     NaN   9347666               NaN
71290      NaN     NaN   9350885               NaN
72514      NaN     NaN   9352109               NaN

[101 rows x 34 columns]

In [182]:
trees_20_alt = df_20[df_20['SERVICECODEDESCRIPTION'] == 'Christmas Tree Collection Concerns']
print(trees_20_alt)

               X          Y SERVICEREQUESTID  \
57     394937.20  145856.38      20-00010030
109    400563.78  135830.91      20-00007334
180    393952.16  140935.75      20-00009390
225    398172.46  140957.60      20-00007683
259    395103.81  140646.84      20-00007715
...          ...        ...              ...
59731  392293.32  140411.12      20-00077057
61352  392374.73  140602.14      20-00079196
66076  398126.06  143072.39      20-00085382
68801  394136.01  144675.24      20-00089929
72069  396604.02  141514.89      20-00095999

                               STREETADDRESS        CITY STATE  ZIPCODE  \
57                       6931 33RD STREET NW  WASHINGTON    DC  20015.0
109                         11 9TH STREET NE  WASHINGTON    DC  20002.0
180    3500 - 3599 BLOCK OF ORDWAY STREET NW  WASHINGTON    DC  20016.0
225                    3645 WARDER STREET NW  WASHINGTON    DC  20010.0
259                    2749 MACOMB STREET NW  WASHINGTON    DC  20008.0
...                                      ...         ...   ...      ...
59731                    3100 45TH STREET NW  WASHINGTON    DC  20016.0
61352                  4434 MACOMB STREET NW  WASHINGTON    DC  20016.0
66076                625 JEFFERSON STREET NW  WASHINGTON    DC  20011.0
68801             3333 RITTENHOUSE STREET NW  WASHINGTON    DC  20015.0
72069                  1712 UPSHUR STREET NW  WASHINGTON    DC  20011.0

         WARD SERVICECODE              SERVICECODEDESCRIPTION  \
57     Ward 4      C62314  Christmas Tree Collection Concerns
109    Ward 6      C62314  Christmas Tree Collection Concerns
180    Ward 3      C62314  Christmas Tree Collection Concerns
225    Ward 1      C62314  Christmas Tree Collection Concerns
259    Ward 3      C62314  Christmas Tree Collection Concerns
...       ...         ...                                 ...
59731  Ward 3      C62314  Christmas Tree Collection Concerns
61352  Ward 3      C62314  Christmas Tree Collection Concerns
66076  Ward 4      C62314  Christmas Tree Collection Concerns
68801  Ward 4      C62314  Christmas Tree Collection Concerns
72069  Ward 4      C62314  Christmas Tree Collection Concerns

      SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  SERVICECALLCOUNT  \
57                           NaN                 OUC                 1
109                          NaN                 OUC                 1
180                          NaN                 OUC                 1
225                          NaN                 OUC                 1
259                          NaN                 OUC                 1
...                          ...                 ...               ...
59731                        NaN                 OUC                 1
61352                        NaN                 OUC                 1
66076                        NaN                 OUC                 1
68801                        NaN                 OUC                 1
72069                        NaN                 OUC                 1

                      ADDDATE          RESOLUTIONDATE          SERVICEDUEDATE  \
57     2020/01/07 17:24:13+00  2022/06/09 02:51:19+00  2020/01/09 04:59:00+00
109    2020/01/06 16:06:08+00  2022/06/09 02:51:19+00  2020/01/08 04:59:00+00
180    2020/01/07 14:13:23+00  2022/06/09 02:51:19+00  2020/01/09 04:59:00+00
225    2020/01/06 18:00:16+00  2022/06/09 02:51:19+00  2020/01/08 04:59:00+00
259    2020/01/06 18:07:18+00  2022/06/09 02:51:19+00  2020/01/08 04:59:00+00
...                       ...                     ...                     ...
59731  2020/03/02 18:01:06+00  2022/06/09 02:51:42+00  2020/03/04 04:59:00+00
61352  2020/03/03 22:26:09+00  2022/06/09 02:51:42+00  2020/03/05 04:59:00+00
66076  2020/03/09 18:06:36+00  2022/06/09 02:51:42+00  2020/03/11 03:59:00+00
68801  2020/03/12 14:26:25+00  2022/06/09 02:51:42+00  2020/03/14 03:59:00+00
72069  2020/03/17 13:46:19+00  2022/06/09 02:51:42+00  2020/03/19 03:59:00+00

             SERVICEORDERDATE  INSPECTIONFLAG  INSPECTIONDATE  INSPECTORNAME  \
57     2020/01/07 17:24:13+00             NaN             NaN            NaN
109    2020/01/06 16:06:08+00             NaN             NaN            NaN
180    2020/01/07 14:13:23+00             NaN             NaN            NaN
225    2020/01/06 18:00:16+00             NaN             NaN            NaN
259    2020/01/06 18:07:18+00             NaN             NaN            NaN
...                       ...             ...             ...            ...
59731  2020/03/02 18:01:06+00             NaN             NaN            NaN
61352  2020/03/03 22:26:09+00             NaN             NaN            NaN
66076  2020/03/09 18:06:36+00             NaN             NaN            NaN
68801  2020/03/12 14:26:25+00             NaN             NaN            NaN
72069  2020/03/17 13:46:19+00             NaN             NaN            NaN

      SERVICEORDERSTATUS  STATUS_CODE DETAILS  PRIORITY     XCOORD  \
57                Closed          NaN     NaN  Standard  394937.20
109               Closed          NaN     NaN  Standard  400563.78
180               Closed          NaN     NaN  Standard  393952.16
225               Closed          NaN     NaN  Standard  398172.46
259               Closed          NaN     NaN  Standard  395103.81
...                  ...          ...     ...       ...        ...
59731             Closed          NaN     NaN  Standard  392293.32
61352             Closed          NaN     NaN  Standard  392374.73
66076             Closed          NaN     NaN  Standard  398126.06
68801             Closed          NaN     NaN  Standard  394136.01
72069             Closed          NaN     NaN  Standard  396604.02

              YCOORD   LATITUDE  LONGITUDE  MARADDRESSREPOSITORYID  \
57     145856.380000  38.980620 -77.058431                261151.0
109    135830.910000  38.890322 -76.993502                 74716.0
180    140935.750007  38.936287 -77.069756                814151.0
225    140957.600000  38.936503 -77.021079                228507.0
259    140646.840000  38.933692 -77.056471                219231.0
...              ...        ...        ...                     ...
59731  140411.120000  38.931548 -77.088883                265279.0
61352  140602.140000  38.933270 -77.087947                274671.0
66076  143072.390000  38.955553 -77.021620                246756.0
68801  144675.240000  38.969975 -77.067668                262537.0
72069  141514.890000  38.941518 -77.039172                258350.0

                                     GLOBALID  CREATED  EDITED  OBJECTID  \
57     {9B922E97-CE1F-E4E4-E053-532F520A122A}      NaN     NaN   9272742
109    {9B922E97-CE83-E4E4-E053-532F520A122A}      NaN     NaN   9272842
180    {9B922E97-CEFB-E4E4-E053-532F520A122A}      NaN     NaN   9272962
225    {9B922E97-CF4B-E4E4-E053-532F520A122A}      NaN     NaN   9273042
259    {9B922E97-CF8C-E4E4-E053-532F520A122A}      NaN     NaN   9273107
...                                       ...      ...     ...       ...
59731  {9FE4CE28-5A51-E01F-E053-532F520A4A6E}      NaN     NaN   9339326
61352  {9FFC49FB-B826-8BC7-E053-532F520A302D}      NaN     NaN   9340947
66076  {A0891B18-5399-8AAB-E053-532F520A3F60}      NaN     NaN   9345671
68801  {A0AAA209-305B-B803-E053-542F520A5596}      NaN     NaN   9348396
72069  {A10E5FAE-D729-EDE7-E053-532F520AE083}      NaN     NaN   9351664

       SE_ANNO_CAD_DATA
57                  NaN
109                 NaN
180                 NaN
225                 NaN
259                 NaN
...                 ...
59731               NaN
61352               NaN
66076               NaN
68801               NaN
72069               NaN

[722 rows x 34 columns]

### Counting rows in new dataframes, which reflect total Christmas tree removal complaints for **2020**.

In [183]:
count_20 = (len(trees_20) + len(trees_20_alt))
print(count_20)

823

# **2: Exporting Annual Complaints As CSV**

## Creating a new dictionary containing complaints per year.

In [184]:
complaints_per_year = {'Year': ['2025', '2024', '2023', '2022', '2021', '2020'], 'Complaints': [count_25, count_24, count_23, count_22, count_21, count_20]}

## Checking the dictionary data is accurate.

In [185]:
print(complaints_per_year)

{'Year': ['2025', '2024', '2023', '2022', '2021', '2020'], 'Complaints': [2742, 1090, 588, 1309, 673, 823]}

## Converting the dictionary to a dataframe.

In [186]:
complaints = pd.DataFrame.from_dict(complaints_per_year)
complaints.head(6)

   Year  Complaints
0  2025        2742
1  2024        1090
2  2023         588
3  2022        1309
4  2021         673
5  2020         823

## Exporting the dataframe to CSV, for upload and visualization in DataWrapper.

In [187]:
complaints.to_csv('complaints.csv')

# **3: Examining Time of Year, 2025 Complaints**

## Creating a new dictionary containing complaints filed during winter snowstorm (Jan. 5 to 6, 2025).

In [188]:
snow_related = df_25[(df_25['ADDDATE'] > '2025/01/04 23:59:59+00') & (df_25['ADDDATE'] < '2025/01/07 00:00:00+00')]

## Checking the dictionary data is accurate.

In [189]:
print(snow_related)

                     X                 Y SERVICEREQUESTID  \
3176  397167.049999997  139214.879999999      25-00006568
3177         392223.07  141901.699999999      25-00006569
3178  396150.850000001  139294.059999999      25-00006570
3179  398760.579999998  144846.670000002      25-00006571
3180  398775.049999997  138324.079999998      25-00006572
...                ...               ...              ...
4856  396555.509999998  139187.690000001      25-00009268
4857  398291.259999998  143271.859999999      25-00009269
4945  400565.140000001  139598.760000002      25-00009633
4947  401650.869999997         134800.66      25-00009635
4949  400494.960000001  136343.649999999      25-00009637

                 STREETADDRESS        CITY STATE ZIPCODE SERVICECODE  \
3176    1417 BELMONT STREET NW  WASHINGTON    DC   20009       S0261
3177     4527 WARREN STREET NW  WASHINGTON    DC   20016       S0031
3178    1833 MINTWOOD PLACE NW  WASHINGTON    DC   20009       S0261
3179      244 WALNUT STREET NW  WASHINGTON    DC   20012       S0031
3180           203 R STREET NW  WASHINGTON    DC   20001       S0031
...                        ...         ...   ...     ...         ...
4856      2319 ONTARIO ROAD NW  WASHINGTON    DC   20009       S0346
4857  450 LONGFELLOW STREET NW  WASHINGTON    DC   20011       S0261
4945      901 EVARTS STREET NE  WASHINGTON    DC   20018       S0261
4947          1631 G STREET SE  WASHINGTON    DC   20003       S0261
4949           814 D STREET NE  WASHINGTON    DC   20002         RPP

                    SERVICECODEDESCRIPTION  \
3176                   Parking Enforcement
3177                       Bulk Collection
3178                   Parking Enforcement
3179                       Bulk Collection
3180                       Bulk Collection
...                                    ...
4856                Sanitation Enforcement
4857                   Parking Enforcement
4945                   Parking Enforcement
4947                   Parking Enforcement
4949  Residential Parking Permit Violation

                             SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
3176  PEMA- Parking Enforcement Management Administr...                 DPW
3177          SWMA- Solid Waste Management Admistration                 DPW
3178  PEMA- Parking Enforcement Management Administr...                 DPW
3179          SWMA- Solid Waste Management Admistration                 DPW
3180          SWMA- Solid Waste Management Admistration                 DPW
...                                                 ...                 ...
4856          SWMA- Solid Waste Management Admistration                 DPW
4857  PEMA- Parking Enforcement Management Administr...                 DPW
4945  PEMA- Parking Enforcement Management Administr...                 DPW
4947  PEMA- Parking Enforcement Management Administr...                 DPW
4949  PEMA- Parking Enforcement Management Administr...                 DPW

     SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
3176                1  2025/01/05 00:02:29+00  2025/01/05 02:58:42+00
3177                1  2025/01/05 00:06:37+00  2025/01/27 15:41:04+00
3178                1  2025/01/05 00:08:30+00  2025/01/05 01:41:33+00
3179                1  2025/01/05 00:09:02+00  2025/01/27 20:11:09+00
3180                1  2025/01/05 00:10:31+00  2025/01/15 15:19:34+00
...               ...                     ...                     ...
4856                1  2025/01/06 23:26:36+00  2025/01/13 17:24:15+00
4857                1  2025/01/06 23:27:14+00  2025/01/08 16:01:03+00
4945                1  2025/01/05 17:07:26+00  2025/01/07 11:16:51+00
4947                1  2025/01/05 16:46:54+00  2025/01/07 11:19:14+00
4949                1  2025/01/05 16:06:29+00  2025/01/07 11:21:01+00

              SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
3176  2025/01/07 00:02:28+00  2025/01/05 00:02:29+00            NaN
3177  2025/01/16 23:59:00+00  2025/01/05 00:06:37+00            NaN
3178  2025/01/07 00:08:30+00  2025/01/05 00:08:30+00            NaN
3179  2025/01/18 04:59:00+00  2025/01/05 00:09:02+00            NaN
3180  2025/01/17 04:59:00+00  2025/01/05 00:10:31+00            NaN
...                      ...                     ...            ...
4856  2025/01/13 23:26:36+00  2025/01/06 23:26:36+00            NaN
4857  2025/01/07 23:27:14+00  2025/01/06 23:27:14+00            NaN
4945  2025/01/06 17:07:26+00  2025/01/05 17:07:26+00            NaN
4947  2025/01/06 16:46:54+00  2025/01/05 16:46:54+00            NaN
4949  2025/01/06 16:06:29+00  2025/01/05 16:06:29+00            NaN

     INSPECTIONDATE INSPECTORNAME    SERVICEORDERSTATUS STATUS_CODE  PRIORITY  \
3176            NaN           NaN                Closed         NaN  Standard
3177            NaN           NaN                Closed         NaN  Standard
3178            NaN           NaN                Closed         NaN  Standard
3179            NaN           NaN                Closed         NaN  Standard
3180            NaN           NaN              Canceled         NaN  Standard
...             ...           ...                   ...         ...       ...
4856            NaN           NaN                Closed         NaN  Standard
4857            NaN           NaN                Closed         NaN  Standard
4945            NaN           NaN  Closed (Transferred)         NaN  Standard
4947            NaN           NaN  Closed (Transferred)         NaN  Standard
4949            NaN           NaN  Closed (Transferred)         NaN  Standard

     DETAILS    WARD     XCOORD     YCOORD     LATITUDE     LONGITUDE  \
3176     NaN  Ward 1  397167.05  139214.88  38.92080091  -77.03266832
3177     NaN  Ward 3  392223.07   141901.7  38.94497507  -77.08971052
3178     NaN  Ward 1  396150.85  139294.06  38.92151066  -77.04438713
3179     NaN  Ward 4  398760.58  144846.67  38.97153768  -77.01430262
3180     NaN  Ward 5  398775.05  138324.08  38.91278033  -77.01412399
...      ...     ...        ...        ...          ...           ...
4856     NaN  Ward 1  396555.51  139187.69  38.92055379  -77.03972019
4857     NaN  Ward 4  398291.26  143271.86  38.95735061  -77.01971453
4945     NaN  Ward 5  400565.14  139598.76  38.92426374  -76.99348274
4947     NaN  Ward 6  401650.87  134800.66  38.88103905  -76.98097351
4949     NaN  Ward 6  400494.96  136343.65  38.89494063  -76.99429441

     MARADDRESSREPOSITORYID                                GLOBALID CREATED  \
3176                 234175  {2AEB70E6-E9CD-1945-E063-782F520A379C}     NaN
3177                 267444  {2AEB70E6-E9CE-1945-E063-782F520A379C}     NaN
3178                 235339  {2AEB70E6-E9CF-1945-E063-782F520A379C}     NaN
3179                 245225  {2AEB70E6-E9D0-1945-E063-782F520A379C}     NaN
3180                 218606  {2AEB70E6-E9D1-1945-E063-782F520A379C}     NaN
...                     ...                                     ...     ...
4856                 235776  {2B130B94-E715-4108-E063-782F520A59BF}     NaN
4857                 248788  {2B130B94-E716-4108-E063-782F520A59BF}     NaN
4945                  81696  {2B1D1A98-2028-4641-E063-782F520A61AA}     NaN
4947                  59053  {2B1D1A98-202A-4641-E063-782F520A61AA}     NaN
4949                  80272  {2B1D1A98-202C-4641-E063-782F520A61AA}     NaN

     EDITED  OBJECTID
3176    NaN  11869399
3177    NaN  11869400
3178    NaN  11869401
3179    NaN  11869402
3180    NaN  11869403
...     ...       ...
4856    NaN  11871735
4857    NaN  11871736
4945    NaN  11871824
4947    NaN  11871826
4949    NaN  11871828

[1453 rows x 33 columns]

## Counting rows, which reflects total complaints lodged during snowstorm.

In [190]:
count_snowstorm = (len(snow_related))
print(count_snowstorm)

1453

## Counting complaints outside snowstorm window.

In [191]:
count_non_snowstorm = (count_25-count_snowstorm)
print(count_non_snowstorm)

1289

# **4: Examining Zip Codes, 2025 Complaints**

## Checking possible zip codes.

In [1]:
zip_codes_test = df_25['ZIPCODE'].unique()
print(zip_codes_test)

NameError: name 'df_25' is not defined

## Creating a new dictionary containing complaints filed in zip code with higher snowfall level (7.7 inches in zip code 20020).

In [193]:
snow_high = snow_related[(snow_related['ZIPCODE'] == '20020')]
print(snow_high)

                     X                 Y SERVICEREQUESTID  \
3432  402277.950000003  131474.989999998      25-00006626
3434  401270.280000001  133428.600000001      25-00006635
3445  402444.840000004  130914.030000001      25-00006683
3451  404639.710000001  133186.710000001      25-00006698
3467  401438.189999998  131928.370000001      25-00006596
...                ...               ...              ...
4826         402289.18  133658.210000001      25-00009070
4830         402351.57  132535.890000001      25-00009209
4832  402643.259999998  131732.760000002      25-00009215
4833  403540.030000001  132302.609999999      25-00009216
4853  404793.138999999  133208.054000001      25-00009262

                                   STREETADDRESS        CITY STATE ZIPCODE  \
3432        ALABAMA AVENUE SE AND 23RD STREET SE  WASHINGTON    DC   20020
3434                         1353 RIDGE PLACE SE  WASHINGTON    DC   20020
3445                         3457 23RD STREET SE  WASHINGTON    DC   20020
3451                         1644 40TH STREET SE  WASHINGTON    DC   20020
3467  2300 - 2399 BLOCK OF GAINESVILLE STREET SE  WASHINGTON    DC   20020
...                                          ...         ...   ...     ...
4826            2210 - 2221 BLOCK OF Q STREET SE  WASHINGTON    DC   20020
4830                       2303 WAGNER STREET SE  WASHINGTON    DC   20020
4832                      2455 ALABAMA AVENUE SE  WASHINGTON    DC   20020
4833                       2521 BRANCH AVENUE SE  WASHINGTON    DC   20020
4853          1700 - 1899 BLOCK OF 41ST PLACE SE  WASHINGTON    DC   20020

      SERVICECODE                SERVICECODEDESCRIPTION  \
3432     SIGTRAMA                  Traffic Signal Issue
3434        S0477                  Scheduled Yard Waste
3445   SERVDCSNOW    Residential Snow Removal (ServeDC)
3451        S0031                       Bulk Collection
3467        S0181                       Illegal Dumping
...           ...                                   ...
4826  SnowIceRP24  Snow and Ice Removal on Public Space
4830   SERVDCSNOW    Residential Snow Removal (ServeDC)
4832  SnowIceRP24  Snow and Ice Removal on Public Space
4833   SERVDCSNOW    Residential Snow Removal (ServeDC)
4853  SnowIceRP24  Snow and Ice Removal on Public Space

                       SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
3432                           Toa- Trans Sys Mnt                DDOT
3434  SWMA- Solid Waste Management Administration                 DPW
3445                                     Serve DC            Serve DC
3451    SWMA- Solid Waste Management Admistration                 DPW
3467    SWMA- Solid Waste Management Admistration                 DPW
...                                           ...                 ...
4826                                          NaN                 DPW
4830                                     Serve DC            Serve DC
4832                                          NaN                 DPW
4833                                     Serve DC            Serve DC
4853                                          NaN                 DPW

     SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
3432                1  2025/01/05 01:51:43+00  2025/01/05 04:13:23+00
3434                1  2025/01/05 02:05:04+00  2025/01/10 22:03:59+00
3445                1  2025/01/05 04:13:55+00  2025/01/05 04:13:55+00
3451                1  2025/01/05 05:17:59+00  2025/01/23 14:26:15+00
3467                1  2025/01/05 00:57:02+00  2025/01/26 20:42:56+00
...               ...                     ...                     ...
4826                1  2025/01/06 21:40:19+00  2025/01/07 10:52:28+00
4830                1  2025/01/06 22:50:44+00  2025/01/06 22:50:44+00
4832                1  2025/01/06 22:54:56+00  2025/01/07 09:39:33+00
4833                1  2025/01/06 22:55:46+00  2025/01/06 22:55:46+00
4853                1  2025/01/06 23:22:04+00  2025/01/07 09:34:52+00

              SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
3432  2025/01/08 01:51:43+00  2025/01/05 01:51:43+00            NaN
3434  2025/01/10 04:59:00+00  2025/01/05 02:05:04+00            NaN
3445  2025/01/06 04:13:55+00  2025/01/05 04:13:55+00            NaN
3451  2025/01/15 04:59:00+00  2025/01/05 05:17:59+00            NaN
3467  2025/01/24 00:57:02+00  2025/01/05 00:57:02+00            NaN
...                      ...                     ...            ...
4826  2025/01/08 21:40:19+00  2025/01/06 21:40:19+00            NaN
4830  2025/01/07 22:50:44+00  2025/01/06 22:50:44+00            NaN
4832  2025/01/08 22:54:56+00  2025/01/06 22:54:56+00            NaN
4833  2025/01/07 22:55:46+00  2025/01/06 22:55:46+00            NaN
4853  2025/01/08 23:22:04+00  2025/01/06 23:22:04+00            NaN

     INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE  PRIORITY  \
3432            NaN           NaN             Closed         NaN  Standard
3434            NaN           NaN             Closed         NaN  Standard
3445            NaN           NaN             Closed         NaN  Standard
3451            NaN           NaN             Closed         NaN  Standard
3467            NaN           NaN             Closed         NaN  Standard
...             ...           ...                ...         ...       ...
4826            NaN           NaN             Closed         NaN  Standard
4830            NaN           NaN             Closed         NaN  Standard
4832            NaN           NaN             Closed         NaN  Standard
4833            NaN           NaN             Closed         NaN  Standard
4853            NaN           NaN             Closed         NaN  Standard

     DETAILS    WARD           XCOORD           YCOORD     LATITUDE  \
3432     NaN  Ward 8  402277.95001607  131474.99000744  38.85107865
3434     NaN  Ward 8        401270.28         133428.6  38.86867996
3445     NaN  Ward 8        402444.84        130914.03  38.84602516
3451     NaN  Ward 7        404639.71        133186.71  38.86648959
3467     NaN  Ward 8        401438.19        131928.37  38.85516467
...      ...     ...              ...              ...          ...
4826     NaN  Ward 8        402289.18        133658.21  38.87074598
4830     NaN  Ward 8        402351.57        132535.89  38.86063583
4832     NaN  Ward 8        402643.26        131732.76  38.85339973
4833     NaN  Ward 7        403540.03        132302.61  38.85853037
4853     NaN  Ward 7   404793.1386584  133208.05362505  38.86668071

         LONGITUDE MARADDRESSREPOSITORYID  \
3432  -76.97375735                 905193
3434  -76.98536239                  65992
3445  -76.97183672                  34413
3451  -76.94653764                  58717
3467  -76.98343068                 807453
...            ...                    ...
4826  -76.97362071                 811433
4830   -76.9729056                  49026
4832  -76.96954788                 278162
4833  -76.95921356                  46326
4853  -76.94476957                 815309

                                    GLOBALID CREATED EDITED  OBJECTID
3432  {2AED1E12-946A-6A59-E063-792F520A338C}     NaN    NaN  11869655
3434  {2AED1E12-946C-6A59-E063-792F520A338C}     NaN    NaN  11869657
3445  {2AEF00E0-D774-7D36-E063-792F520AA1CE}     NaN    NaN  11869668
3451  {2AF4A93C-1618-2622-E063-792F520A319B}     NaN    NaN  11869674
3467  {2AEC3C31-B4E5-511E-E063-782F520AA19D}     NaN    NaN  11869738
...                                      ...     ...    ...       ...
4826  {2B119414-A2FF-0AAE-E063-782F520A0CBE}     NaN    NaN  11871705
4830  {2B130B94-E6FB-4108-E063-782F520A59BF}     NaN    NaN  11871709
4832  {2B130B94-E6FD-4108-E063-782F520A59BF}     NaN    NaN  11871711
4833  {2B130B94-E6FE-4108-E063-782F520A59BF}     NaN    NaN  11871712
4853  {2B130B94-E712-4108-E063-782F520A59BF}     NaN    NaN  11871732

[146 rows x 33 columns]

## Counting rows, which reflects total complaints in zip code 20020.

In [194]:
count_high_snow = (len(snow_high))
print(count_high_snow)

146

## Creating a new dictionary containing complaints filed in zip code with lower snowfall level (6.3 inches in zip code 20016).

In [195]:
snow_low = snow_related[(snow_related['ZIPCODE'] == '20016')]
print(snow_low)

                     X                 Y SERVICEREQUESTID  \
3177         392223.07  141901.699999999      25-00006569
3471  391859.420000002  142116.449999999      25-00006599
3483  392400.630000003  140774.530000001      25-00006640
3490  391910.020000003  141040.309999999      25-00006647
3497  393346.780000001  141809.100000001      25-00006655
3498  392414.259999998  143071.539999999      25-00006656
3504  391045.859999999  140776.370000001      25-00006670
3541  392653.399999999  142777.920000002      25-00006906
3574  391043.270000003  140816.030000001      25-00007043
3580  393118.270000003         142073.27      25-00007050
3597  392914.090000004  142467.550000001      25-00007090
3600  392914.090000004  142467.550000001      25-00007093
3616  392914.090000004  142467.550000001      25-00007111
3642  391487.630000003  139778.800000001      25-00007171
3830  390869.939999998  139920.809999999      25-00006811
3850  392236.140000001  142519.809999999      25-00006845
3879  393892.729999997  141168.289999999      25-00006885
3915  393745.380000003         140540.77      25-00006961
3920  393509.880000003  140100.280000001      25-00006973
3956  390477.670000002         140564.59      25-00007018
3961         391794.93         141202.32      25-00007026
3968  393014.869999997         143099.73      25-00007037
3980  392547.200000003  142117.640000001      25-00007089
3981  392598.090000004  141401.190000001      25-00007128
3992  393394.490000002  141635.280000001      25-00007144
3993  392252.090000004  140593.079999998      25-00007146
4008  390532.780000001  140020.149999999      25-00007201
4026  391391.539999999  139938.489999998      25-00007234
4076  393605.229999997  141766.739999998      25-00007526
4090  390381.439999998  140712.030000001      25-00007714
4157         392602.07  142806.379999999      25-00007787
4160  392368.409999996  143005.219999999      25-00007794
4170  392293.109999999  140470.800000001      25-00007808
4176  391836.579999998         141749.23      25-00007816
4220  393673.710000001  142558.539999999      25-00007960
4238  390523.289999999          140137.5      25-00008050
4253  392380.799999997  142206.850000001      25-00008085
4345         392677.93  142847.789999999      25-00008293
4476  393554.240000002         142164.66      25-00008226
4545  393538.369999997  140151.670000002      25-00008452
4625  393606.479999997  140129.960000001      25-00008833
4684  390781.850000001         140384.43      25-00008978
4702         391026.07  140998.809999999      25-00009090
4720  392696.649999999         142807.02      25-00009134
4837  391556.729999997          142612.0      25-00009226

                                        STREETADDRESS        CITY STATE  \
3177                            4527 WARREN STREET NW  WASHINGTON    DC
3471                              4724 ALTON PLACE NW  WASHINGTON    DC
3483                          3401 NEBRASKA AVENUE NW  WASHINGTON    DC
3490                             4703 WOODWAY LANE NW  WASHINGTON    DC
3497                            3831 VEAZEY STREET NW  WASHINGTON    DC
3498                            4433 FARADAY PLACE NW  WASHINGTON    DC
3504                        5014 GLENBROOK TERRACE NW  WASHINGTON    DC
3541                               4823 43RD PLACE NW  WASHINGTON    DC
3574                        5021 GLENBROOK TERRACE NW  WASHINGTON    DC
3580                         4400 WISCONSIN AVENUE NW  WASHINGTON    DC
3597                               4127 RIVER ROAD NW  WASHINGTON    DC
3600                               4127 RIVER ROAD NW  WASHINGTON    DC
3616                               4127 RIVER ROAD NW  WASHINGTON    DC
3642                            2809 BATTERY PLACE NW  WASHINGTON    DC
3830           ARIZONA AVENUE NW AND SHERIER PLACE NW  WASHINGTON    DC
3850                         4521 BURLINGTON PLACE NW  WASHINGTON    DC
3879                            3539 QUEBEC STREET NW  WASHINGTON    DC
3915                         3201 WISCONSIN AVENUE NW  WASHINGTON    DC
3920                         3800 CATHEDRAL AVENUE NW  WASHINGTON    DC
3956                      5714 MACARTHUR BOULEVARD NW  WASHINGTON    DC
3961                              3712 48TH STREET NW  WASHINGTON    DC
3968                          4102 GARRISON STREET NW  WASHINGTON    DC
3980                              4356 ALTON PLACE NW  WASHINGTON    DC
3981                              3916 44TH STREET NW  WASHINGTON    DC
3992                         4105 WISCONSIN AVENUE NW  WASHINGTON    DC
3993                            4508 MACOMB STREET NW  WASHINGTON    DC
4008                           5437 POTOMAC AVENUE NW  WASHINGTON    DC
4026                         4938 ESKRIDGE TERRACE NW  WASHINGTON    DC
4076                            3728 VEAZEY STREET NW  WASHINGTON    DC
4090                      5758 MACARTHUR BOULEVARD NW  WASHINGTON    DC
4157                          4336 ELLICOTT STREET NW  WASHINGTON    DC
4160                         4435 FESSENDEN STREET NW  WASHINGTON    DC
4170                              3118 45TH STREET NW  WASHINGTON    DC
4176                     4724 MASSACHUSETTS AVENUE NW  WASHINGTON    DC
4220                        3727 CHESAPEAKE STREET NW  WASHINGTON    DC
4238                           5510 CAROLINA PLACE NW  WASHINGTON    DC
4253                         4436 ALBEMARLE STREET NW  WASHINGTON    DC
4345                          4315 ELLICOTT STREET NW  WASHINGTON    DC
4476                              4411 38TH STREET NW  WASHINGTON    DC
4545                     3706 MASSACHUSETTS AVENUE NW  WASHINGTON    DC
4625  MASSACHUSETTS AVENUE NW AND CATHEDRAL AVENUE NW  WASHINGTON    DC
4684                          5532 HAWTHORNE PLACE NW  WASHINGTON    DC
4702            3500 - 3599 BLOCK OF OVERLOOK LANE NW  WASHINGTON    DC
4720                          4308 ELLICOTT STREET NW  WASHINGTON    DC
4837                           4711 WESTERN AVENUE NW  WASHINGTON    DC

     ZIPCODE  SERVICECODE                             SERVICECODEDESCRIPTION  \
3177   20016        S0031                                    Bulk Collection
3471   20016        S0441                          Trash Collection - Missed
3483   20016        S0459                                       Tree Removal
3490   20016        S0441                          Trash Collection - Missed
3497   20016        S0217                 Public Space Litter Can-Collection
3498   20016        S05SL                   Streetlight Repair Investigation
3504   20016        S0031                                    Bulk Collection
3541   20016        S0016                                       Alley Repair
3574   20016        S0477                               Scheduled Yard Waste
3580   20016     MARKINST                        Roadway Striping / Markings
3597   20016        S0422                                Supercan - Delivery
3600   20016        S0316                            Recycling Cart Delivery
3616   20016        S0441                          Trash Collection - Missed
3642   20016     CONTREMO                                  Container Removal
3830   20016        S0301                                            Pothole
3850   20016        S0457                                    Tree Inspection
3879   20016        S0031                                    Bulk Collection
3915   20016        S0217                 Public Space Litter Can-Collection
3920   20016        S0196                            Leaf  Collection Missed
3956   20016        S0031                                    Bulk Collection
3961   20016        S0477                               Scheduled Yard Waste
3968   20016        S0031                                    Bulk Collection
3980   20016        S0031                                    Bulk Collection
3981   20016        S0031                                    Bulk Collection
3992   20016  SIGNMISS_v2                                      Roadway Signs
3993   20016        S0441                          Trash Collection - Missed
4008   20016        S0477                               Scheduled Yard Waste
4026   20016  SnowIceRP24               Snow and Ice Removal on Public Space
4076   20016      COMPOST  Lost/Stolen Compost Bin, Broken Compost Bin or...
4090   20016        S0451                              Trash Cart - Delivery
4157   20016        S0031                                    Bulk Collection
4160   20016        S0031                                    Bulk Collection
4170   20016   SERVDCSNOW                 Residential Snow Removal (ServeDC)
4176   20016   SERVDCSNOW                 Residential Snow Removal (ServeDC)
4220   20016   SERVDCSNOW                 Residential Snow Removal (ServeDC)
4238   20016        S0031                                    Bulk Collection
4253   20016   SERVDCSNOW                 Residential Snow Removal (ServeDC)
4345   20016        S0031                                    Bulk Collection
4476   20016   SERVDCSNOW                 Residential Snow Removal (ServeDC)
4545   20016        S0261                                Parking Enforcement
4625   20016     SIGTRAMA                               Traffic Signal Issue
4684   20016        S0031                                    Bulk Collection
4702   20016  SnowIceRP24               Snow and Ice Removal on Public Space
4720   20016        S0031                                    Bulk Collection
4837   20016        S0031                                    Bulk Collection

                             SERVICETYPECODEDESCRIPTION ORGANIZATIONACRONYM  \
3177          SWMA- Solid Waste Management Admistration                 DPW
3471          SWMA- Solid Waste Management Admistration                 DPW
3483                                    Urban Forrestry                DDOT
3490          SWMA- Solid Waste Management Admistration                 DPW
3497          SWMA- Solid Waste Management Admistration                 DPW
3498           Transportation Operations Administration                DDOT
3504          SWMA- Solid Waste Management Admistration                 DPW
3541                                               SIOD                DDOT
3574        SWMA- Solid Waste Management Administration                 DPW
3580           Transportation Operations Administration                DDOT
3597          SWMA- Solid Waste Management Admistration                 DPW
3600          SWMA- Solid Waste Management Admistration                 DPW
3616          SWMA- Solid Waste Management Admistration                 DPW
3642          SWMA- Solid Waste Management Admistration                 DPW
3830                    Toa-Street & Bridge Maintenance                DDOT
3850                                    Urban Forrestry                DDOT
3879          SWMA- Solid Waste Management Admistration                 DPW
3915          SWMA- Solid Waste Management Admistration                 DPW
3920          SWMA- Solid Waste Management Admistration                 DPW
3956          SWMA- Solid Waste Management Admistration                 DPW
3961        SWMA- Solid Waste Management Administration                 DPW
3968          SWMA- Solid Waste Management Admistration                 DPW
3980          SWMA- Solid Waste Management Admistration                 DPW
3981          SWMA- Solid Waste Management Admistration                 DPW
3992                                                NaN                DDOT
3993          SWMA- Solid Waste Management Admistration                 DPW
4008        SWMA- Solid Waste Management Administration                 DPW
4026                                                NaN                 DPW
4076                                                NaN                 DPW
4090          SWMA- Solid Waste Management Admistration                 DPW
4157          SWMA- Solid Waste Management Admistration                 DPW
4160          SWMA- Solid Waste Management Admistration                 DPW
4170                                           Serve DC            Serve DC
4176                                           Serve DC            Serve DC
4220                                           Serve DC            Serve DC
4238          SWMA- Solid Waste Management Admistration                 DPW
4253                                           Serve DC            Serve DC
4345          SWMA- Solid Waste Management Admistration                 DPW
4476                                           Serve DC            Serve DC
4545  PEMA- Parking Enforcement Management Administr...                 DPW
4625                                 Toa- Trans Sys Mnt                DDOT
4684          SWMA- Solid Waste Management Admistration                 DPW
4702                                                NaN                 DPW
4720          SWMA- Solid Waste Management Admistration                 DPW
4837          SWMA- Solid Waste Management Admistration                 DPW

     SERVICECALLCOUNT                 ADDDATE          RESOLUTIONDATE  \
3177                1  2025/01/05 00:06:37+00  2025/01/27 15:41:04+00
3471                1  2025/01/05 01:06:05+00  2025/01/07 17:01:43+00
3483                1  2025/01/05 02:12:36+00  2025/01/06 14:44:02+00
3490                1  2025/01/05 02:34:27+00  2025/01/07 17:01:50+00
3497                1  2025/01/05 02:45:15+00  2025/01/05 05:01:29+00
3498                1  2025/01/05 02:47:18+00  2025/01/08 15:09:29+00
3504                1  2025/01/05 03:35:41+00  2025/01/27 14:45:56+00
3541                1  2025/01/05 16:47:46+00                     NaN
3574                1  2025/01/05 19:20:53+00  2025/01/14 17:04:53+00
3580                1  2025/01/05 19:27:15+00  2025/05/30 15:06:26+00
3597                1  2025/01/05 19:58:37+00  2025/01/21 14:52:34+00
3600                1  2025/01/05 20:03:12+00  2025/01/21 14:52:48+00
3616                1  2025/01/05 20:15:29+00  2025/01/07 17:02:03+00
3642                1  2025/01/05 21:27:17+00  2025/02/18 15:04:02+00
3830                1  2025/01/05 14:43:30+00  2025/01/10 18:28:52+00
3850                1  2025/01/05 15:29:49+00  2025/01/06 12:43:33+00
3879                1  2025/01/05 16:18:16+00  2025/01/27 16:31:13+00
3915                1  2025/01/05 18:02:37+00  2025/01/14 07:00:59+00
3920                1  2025/01/05 18:11:53+00  2025/01/30 18:00:07+00
3956                1  2025/01/05 18:53:18+00  2025/01/27 14:36:13+00
3961                1  2025/01/05 19:04:54+00  2025/01/14 16:03:11+00
3968                1  2025/01/05 19:10:30+00  2025/01/27 18:01:28+00
3980                1  2025/01/05 19:56:45+00  2025/01/27 15:36:22+00
3981                1  2025/01/05 20:27:57+00  2025/01/27 16:01:08+00
3992                1  2025/01/05 20:45:08+00  2025/01/14 18:04:03+00
3993                1  2025/01/05 20:46:17+00  2025/01/08 18:02:34+00
4008                1  2025/01/05 21:59:56+00  2025/01/14 17:05:07+00
4026                1  2025/01/05 22:39:12+00  2025/01/06 01:06:15+00
4076                1  2025/01/06 12:39:25+00  2025/01/07 17:10:46+00
4090                1  2025/01/06 14:19:56+00  2025/01/22 12:32:22+00
4157                1  2025/01/06 14:48:34+00  2025/01/27 15:21:04+00
4160                1  2025/01/06 14:50:56+00  2025/01/27 15:11:14+00
4170                1  2025/01/06 14:55:37+00  2025/01/06 14:55:37+00
4176                1  2025/01/06 14:59:44+00  2025/01/06 14:59:44+00
4220                1  2025/01/06 15:47:02+00  2025/01/06 15:47:02+00
4238                1  2025/01/06 16:16:26+00  2025/01/27 14:16:08+00
4253                1  2025/01/06 16:26:07+00  2025/01/06 16:26:07+00
4345                1  2025/01/06 17:26:46+00  2025/01/27 15:11:21+00
4476                1  2025/01/06 17:04:34+00  2025/01/06 17:04:34+00
4545                1  2025/01/06 18:13:32+00  2025/01/08 15:56:23+00
4625                1  2025/01/06 20:14:33+00  2025/01/07 17:13:32+00
4684                1  2025/01/06 20:58:48+00  2025/01/27 14:31:25+00
4702                1  2025/01/06 21:48:12+00  2025/01/07 10:53:40+00
4720                1  2025/01/06 22:12:58+00  2025/01/27 15:16:05+00
4837                1  2025/01/06 23:04:25+00  2025/01/27 15:01:19+00

              SERVICEDUEDATE        SERVICEORDERDATE INSPECTIONFLAG  \
3177  2025/01/16 23:59:00+00  2025/01/05 00:06:37+00            NaN
3471  2025/01/08 01:06:05+00  2025/01/05 01:06:05+00            NaN
3483  2025/09/24 02:12:36+00  2025/01/05 02:12:36+00            NaN
3490  2025/01/08 02:34:27+00  2025/01/05 02:34:27+00            NaN
3497  2025/01/07 02:45:15+00  2025/01/05 02:45:15+00            NaN
3498  2025/01/15 02:47:18+00  2025/01/05 02:47:18+00            NaN
3504  2025/01/17 04:59:00+00  2025/01/05 03:35:41+00            NaN
3541  2026/02/02 16:47:46+00  2025/01/05 16:47:46+00            NaN
3574  2025/01/15 04:59:00+00  2025/01/05 19:20:53+00            NaN
3580  2026/02/02 19:27:14+00  2025/01/05 19:27:15+00            NaN
3597  2025/02/03 19:58:37+00  2025/01/05 19:58:37+00            NaN
3600  2025/02/03 20:03:12+00  2025/01/05 20:03:12+00            NaN
3616  2025/01/07 20:15:29+00  2025/01/05 20:15:29+00            NaN
3642  2025/02/03 21:27:17+00  2025/01/05 21:27:17+00            NaN
3830  2025/01/08 14:43:30+00  2025/01/05 14:43:30+00            NaN
3850  2025/01/10 15:29:49+00  2025/01/05 15:29:49+00            NaN
3879  2025/01/17 04:59:00+00  2025/01/05 16:18:16+00            NaN
3915  2025/01/07 18:02:37+00  2025/01/05 18:02:37+00            NaN
3920  2025/01/15 18:11:53+00  2025/01/05 18:11:53+00            NaN
3956  2025/01/17 04:59:00+00  2025/01/05 18:53:18+00            NaN
3961  2025/01/15 04:59:00+00  2025/01/05 19:04:54+00            NaN
3968  2025/01/17 04:59:00+00  2025/01/05 19:10:30+00            NaN
3980  2025/01/17 04:59:00+00  2025/01/05 19:56:45+00            NaN
3981  2025/01/17 04:59:00+00  2025/01/05 20:27:57+00            NaN
3992  2025/07/14 20:45:08+00  2025/01/05 20:45:08+00            NaN
3993  2025/01/07 20:46:17+00  2025/01/05 20:46:17+00            NaN
4008  2025/01/14 23:59:00+00  2025/01/05 21:59:56+00            NaN
4026  2025/01/07 22:39:11+00  2025/01/05 22:39:12+00            NaN
4076  2025/01/28 12:39:25+00  2025/01/06 12:39:25+00            NaN
4090  2025/02/04 14:19:56+00  2025/01/06 14:19:56+00            NaN
4157  2025/01/17 04:59:00+00  2025/01/06 14:48:34+00            NaN
4160  2025/01/17 04:59:00+00  2025/01/06 14:50:56+00            NaN
4170  2025/01/07 14:55:37+00  2025/01/06 14:55:37+00            NaN
4176  2025/01/07 14:59:44+00  2025/01/06 14:59:44+00            NaN
4220  2025/01/07 15:47:02+00  2025/01/06 15:47:02+00            NaN
4238  2025/01/17 04:59:00+00  2025/01/06 16:16:26+00            NaN
4253  2025/01/07 16:26:07+00  2025/01/06 16:26:07+00            NaN
4345  2025/01/17 04:59:00+00  2025/01/06 17:26:46+00            NaN
4476  2025/01/07 17:04:34+00  2025/01/06 17:04:34+00            NaN
4545  2025/01/07 18:13:32+00  2025/01/06 18:13:32+00            NaN
4625  2025/01/08 20:14:33+00  2025/01/06 20:14:33+00            NaN
4684  2025/01/17 04:59:00+00  2025/01/06 20:58:48+00            NaN
4702  2025/01/08 21:48:12+00  2025/01/06 21:48:12+00            NaN
4720  2025/01/17 04:59:00+00  2025/01/06 22:12:58+00            NaN
4837  2025/01/17 04:59:00+00  2025/01/06 23:04:25+00            NaN

     INSPECTIONDATE INSPECTORNAME SERVICEORDERSTATUS STATUS_CODE  PRIORITY  \
3177            NaN           NaN             Closed         NaN  Standard
3471            NaN           NaN             Closed         NaN  Standard
3483            NaN           NaN             Closed         NaN  Standard
3490            NaN           NaN             Closed         NaN  Standard
3497            NaN           NaN             Closed         NaN  Standard
3498            NaN           NaN             Closed         NaN  Standard
3504            NaN           NaN             Closed         NaN  Standard

## Counting rows, which reflects total complaints in zip code 20016.

In [196]:
count_low_snow = (len(snow_low))
print(count_low_snow)

45

## Moving zip code counts into a dataframe.

In [197]:
zipcodes = {'Zipcode': ['20020', '20016'], 'Complaints': [count_high_snow, count_low_snow]}
zipcodes_count = pd.DataFrame.from_dict(zipcodes)
zipcodes_count.head()

  Zipcode  Complaints
0   20020         146
1   20016          45

## Exporting the dataframe to CSV, for upload and visualization in DataWrapper.

In [198]:
zipcodes_count.to_csv('zipcodes.csv')

## Finding most common zip code for call entries to help standardize colors.

In [210]:
most_common_zip = snow_related.ZIPCODE.mode()

In [211]:
print(most_common_zip)

0    20011
Name: ZIPCODE, dtype: object

## Counting the number of calls in the most commonly entered zip code to set as maximum on color scale.

In [3]:
zip_high = snow_related[(snow_related['ZIPCODE'] == '20011')]
print(zip_high)

NameError: name 'snow_related' is not defined

## Returning the count.

In [214]:
zip_count_max = (len(zip_high))
print(zip_count_max)

188