In [86]:
import pandas as pd

In [87]:
# Importing tree count CSV file

tree_df = pd.read_csv("tree-count-2015.csv")
tree_df

     Zip code  Tree count
0       10312       22186
1       10314       16905
2       10306       13030
3       10309       12650
4       11234       11253
..        ...         ...
186     10111          25
187     11451          12
188     10048          12
189     11096           9
190     10115           7

[191 rows x 2 columns]

In [88]:
## Checking data types

tree_df["Zip code"].dtype

dtype('int64')

In [89]:
tree_df["Tree count"].dtype

dtype('int64')

In [90]:
## Converting Zip code from int to string, and converting Tree count to int

tree_df["Zip code"] = (
    tree_df["Zip code"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
)

tree_df["Tree count"] = pd.to_numeric(tree_df["Tree count"], errors="coerce").astype("Int64")

In [91]:
tree_df

    Zip code  Tree count
0      10312       22186
1      10314       16905
2      10306       13030
3      10309       12650
4      11234       11253
..       ...         ...
186    10111          25
187    11451          12
188    10048          12
189    11096           9
190    10115           7

[191 rows x 2 columns]

In [92]:
# Import complaints CSV file

zip_df = pd.read_csv("zip_counts_updated.csv")

zip_df

     Incident Zip  Count
0         11234.0   2355
1         10312.0   1622
2         10314.0   1454
3         10306.0   1384
4         11385.0   1224
..            ...    ...
177       11697.0      2
178       10281.0      1
179       10280.0      1
180       11109.0      1
181       10282.0      1

[182 rows x 2 columns]

In [93]:
# Checking data types

zip_df["Incident Zip"].dtype

dtype('float64')

In [94]:
zip_df["Count"].dtype

dtype('int64')

In [95]:
# Converting Incident Zip to string

zip_df["Incident Zip"] = (
    zip_df["Incident Zip"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
)

zip_df

    Incident Zip  Count
0          11234   2355
1          10312   1622
2          10314   1454
3          10306   1384
4          11385   1224
..           ...    ...
177        11697      2
178        10281      1
179        10280      1
180        11109      1
181        10282      1

[182 rows x 2 columns]

In [96]:
# Merge
combined_df = pd.merge(
    zip_df,
    tree_df,
    left_on="Incident Zip",
    right_on="Zip code",
    how="inner"
)

In [97]:
# New column
combined_df["Complaints per Tree"] = combined_df["Count"] / combined_df["Tree count"]

In [98]:
# Test
combined_df

    Incident Zip  Count Zip code  Tree count  Complaints per Tree
0          11234   2355    11234       11253             0.209278
1          10312   1622    10312       22186             0.073109
2          10314   1454    10314       16905              0.08601
3          10306   1384    10306       13030             0.106216
4          11385   1224    11385       10937             0.111914
..           ...    ...      ...         ...                  ...
174        11697      2    11697          30             0.066667
175        10281      1    10281          72             0.013889
176        10280      1    10280         418             0.002392
177        11109      1    11109          92              0.01087
178        10282      1    10282         234             0.004274

[179 rows x 5 columns]

In [99]:
combined_df.to_csv("combined_df.csv", index=False)

In [100]:
combined_df = combined_df.sort_values(
    by="Complaints per Tree",
    ascending=False
).reset_index(drop=True)

combined_df

    Incident Zip  Count Zip code  Tree count  Complaints per Tree
0          11419    625    11419        2805             0.222816
1          11203   1082    11203        5141             0.210465
2          11234   2355    11234       11253             0.209278
3          11412    903    11412        4697              0.19225
4          11421    539    11421        2855             0.188792
..           ...    ...      ...         ...                  ...
174        10281      1    10281          72             0.013889
175        11109      1    11109          92              0.01087
176        10474     20    10474        2644             0.007564
177        10282      1    10282         234             0.004274
178        10280      1    10280         418             0.002392

[179 rows x 5 columns]